package spell

type spellSeed struct {
	id              SpellID
	school          SchoolID
	descriptors     []DescriptorID
	components      []ComponentID
	castingTime     string
	spellRange      string
	targetEffect    string
	duration        string
	savingThrow     string
	spellResistance string
}

var coreSpells = mustBuildCoreSpells(coreSpellSeeds)

var coreSpellSeeds = []spellSeed{
	{
		id:              SpellID("Acid Splash"),
		school:          ConjurationSchoolID,
		descriptors:     []DescriptorID{"Acid"},
		components:      []ComponentID{VerbalComponentID, SomaticComponentID},
		castingTime:     "1 standard action",
		spellRange:      "close (25 ft. + 5 ft./2 levels)",
		targetEffect:    "one missile of acid",
		duration:        "instantaneous",
		savingThrow:     "none",
		spellResistance: "no",
	},
	{
		id:              SpellID("Arcane Mark"),
		school:          UniversalSchoolID,
		components:      []ComponentID{VerbalComponentID, SomaticComponentID},
		castingTime:     "1 standard action",
		spellRange:      "touch",
		targetEffect:    "one personal rune or mark, all of which must fit within 1 sq. ft.",
		duration:        "permanent",
		savingThrow:     "none",
		spellResistance: "no",
	},
	{
		id:              SpellID("Bleed"),
		school:          NecromancySchoolID,
		components:      []ComponentID{VerbalComponentID, SomaticComponentID},
		castingTime:     "1 standard action",
		spellRange:      "close (25 ft. + 5 ft./2 levels)",
		targetEffect:    "one living creature",
		duration:        "instantaneous",
		savingThrow:     "Will negates",
		spellResistance: "yes",
	},
	{
		id:              SpellID("Create Water"),
		school:          ConjurationSchoolID,
		descriptors:     []DescriptorID{"Water"},
		components:      []ComponentID{VerbalComponentID, SomaticComponentID},
		castingTime:     "1 standard action",
		spellRange:      "close (25 ft. + 5 ft./2 levels)",
		targetEffect:    "up to 2 gallons of water/level",
		duration:        "instantaneous",
		savingThrow:     "none",
		spellResistance: "no",
	},
	{
		id:              SpellID("Dancing Lights"),
		school:          EvocationSchoolID,
		descriptors:     []DescriptorID{"Light"},
		components:      []ComponentID{VerbalComponentID, SomaticComponentID},
		castingTime:     "1 standard action",
		spellRange:      "medium (100 ft. + 10 ft./level)",
		targetEffect:    "up to four lights, all within a 10-ft.-radius area",
		duration:        "1 minute (D)",
		savingThrow:     "none",
		spellResistance: "no",
	},
	{
		id:              SpellID("Daze"),
		school:          EnchantmentSchoolID,
		descriptors:     []DescriptorID{"Mind-Affecting"},
		components:      []ComponentID{VerbalComponentID, SomaticComponentID, MaterialComponentID},
		castingTime:     "1 standard action",
		spellRange:      "close (25 ft. + 5 ft./2 levels)",
		targetEffect:    "one humanoid creature of 4 HD or less",
		duration:        "1 round",
		savingThrow:     "Will negates",
		spellResistance: "yes",
	},
	{
		id:              SpellID("Detect Magic"),
		school:          DivinationSchoolID,
		components:      []ComponentID{VerbalComponentID, SomaticComponentID},
		castingTime:     "1 standard action",
		spellRange:      "60 ft.",
		targetEffect:    "cone-shaped emanation",
		duration:        "concentration, up to 1 min./level (D)",
		savingThrow:     "none",
		spellResistance: "no",
	},
	{
		id:              SpellID("Detect Poison"),
		school:          DivinationSchoolID,
		components:      []ComponentID{VerbalComponentID, SomaticComponentID},
		castingTime:     "1 standard action",
		spellRange:      "close (25 ft. + 5 ft./2 levels)",
		targetEffect:    "one creature, one object, or a 5-ft. cube",
		duration:        "instantaneous",
		savingThrow:     "none",
		spellResistance: "no",
	},
	{
		id:              SpellID("Disrupt Undead"),
		school:          NecromancySchoolID,
		components:      []ComponentID{VerbalComponentID, SomaticComponentID},
		castingTime:     "1 standard action",
		spellRange:      "close (25 ft. + 5 ft./2 levels)",
		targetEffect:    "ray",
		duration:        "instantaneous",
		savingThrow:     "none",
		spellResistance: "yes",
	},
	{
		id:              SpellID("Flare"),
		school:          EvocationSchoolID,
		descriptors:     []DescriptorID{"Light"},
		components:      []ComponentID{VerbalComponentID},
		castingTime:     "1 standard action",
		spellRange:      "close (25 ft. + 5 ft./2 levels)",
		targetEffect:    "burst of light",
		duration:        "instantaneous",
		savingThrow:     "Fortitude negates",
		spellResistance: "yes",
	},
	{
		id:              SpellID("Ghost Sound"),
		school:          IllusionSchoolID,
		components:      []ComponentID{VerbalComponentID, SomaticComponentID, MaterialComponentID},
		castingTime:     "1 standard action",
		spellRange:      "close (25 ft. + 5 ft./2 levels)",
		targetEffect:    "illusory sounds",
		duration:        "1 round/level (D)",
		savingThrow:     "Will disbelief",
		spellResistance: "no",
	},
	{
		id:              SpellID("Guidance"),
		school:          DivinationSchoolID,
		components:      []ComponentID{VerbalComponentID, SomaticComponentID},
		castingTime:     "1 standard action",
		spellRange:      "touch",
		targetEffect:    "creature touched",
		duration:        "1 minute or until discharged",
		savingThrow:     "Will negates (harmless)",
		spellResistance: "yes",
	},
	{
		id:              SpellID("Know Direction"),
		school:          DivinationSchoolID,
		components:      []ComponentID{VerbalComponentID, SomaticComponentID},
		castingTime:     "1 standard action",
		spellRange:      "personal",
		targetEffect:    "you",
		duration:        "instantaneous",
		savingThrow:     "none",
		spellResistance: "no",
	},
	{
		id:              SpellID("Light"),
		school:          EvocationSchoolID,
		descriptors:     []DescriptorID{"Light"},
		components:      []ComponentID{VerbalComponentID, MaterialComponentID, DivineFocusComponentID},
		castingTime:     "1 standard action",
		spellRange:      "touch",
		targetEffect:    "object touched",
		duration:        "10 min./level",
		savingThrow:     "none",
		spellResistance: "no",
	},
	{
		id:              SpellID("Lullaby"),
		school:          EnchantmentSchoolID,
		descriptors:     []DescriptorID{"Mind-Affecting"},
		components:      []ComponentID{VerbalComponentID, SomaticComponentID},
		castingTime:     "1 standard action",
		spellRange:      "medium (100 ft. + 10 ft./level)",
		targetEffect:    "living creatures within a 10-ft.-radius burst",
		duration:        "concentration + 1 round/level (D)",
		savingThrow:     "Will negates",
		spellResistance: "yes",
	},
	{
		id:              SpellID("Mage Hand"),
		school:          TransmutationSchoolID,
		components:      []ComponentID{VerbalComponentID, SomaticComponentID},
		castingTime:     "1 standard action",
		spellRange:      "close (25 ft. + 5 ft./2 levels)",
		targetEffect:    "one nonmagical, unattended object weighing up to 5 lbs.",
		duration:        "concentration",
		savingThrow:     "none",
		spellResistance: "no",
	},
	{
		id:              SpellID("Mending"),
		school:          TransmutationSchoolID,
		components:      []ComponentID{VerbalComponentID, SomaticComponentID},
		castingTime:     "10 minutes",
		spellRange:      "10 ft.",
		targetEffect:    "one object of up to 1 lb./level",
		duration:        "instantaneous",
		savingThrow:     "Will negates (harmless, object)",
		spellResistance: "yes (harmless, object)",
	},
	{
		id:              SpellID("Message"),
		school:          TransmutationSchoolID,
		descriptors:     []DescriptorID{"Language-Dependent"},
		components:      []ComponentID{VerbalComponentID, SomaticComponentID, FocusComponentID},
		castingTime:     "1 standard action",
		spellRange:      "medium (100 ft. + 10 ft./level)",
		targetEffect:    "one creature/level",
		duration:        "10 min./level",
		savingThrow:     "none",
		spellResistance: "no",
	},
	{
		id:              SpellID("Open/Close"),
		school:          TransmutationSchoolID,
		components:      []ComponentID{VerbalComponentID, SomaticComponentID, FocusComponentID},
		castingTime:     "1 standard action",
		spellRange:      "close (25 ft. + 5 ft./2 levels)",
		targetEffect:    "object weighing up to 30 lbs. or portal that can be opened or closed",
		duration:        "instantaneous",
		savingThrow:     "Will negates (object)",
		spellResistance: "yes (object)",
	},
	{
		id:              SpellID("Prestidigitation"),
		school:          UniversalSchoolID,
		components:      []ComponentID{VerbalComponentID, SomaticComponentID},
		castingTime:     "1 standard action",
		spellRange:      "10 ft.",
		targetEffect:    "see text",
		duration:        "1 hour",
		savingThrow:     "see text",
		spellResistance: "no",
	},
	{
		id:              SpellID("Purify Food and Drink"),
		school:          TransmutationSchoolID,
		components:      []ComponentID{VerbalComponentID, SomaticComponentID},
		castingTime:     "1 standard action",
		spellRange:      "10 ft.",
		targetEffect:    "1 cu. ft./level of contaminated food and water",
		duration:        "instantaneous",
		savingThrow:     "Will negates (object)",
		spellResistance: "yes (object)",
	},
	{
		id:              SpellID("Ray of Frost"),
		school:          EvocationSchoolID,
		descriptors:     []DescriptorID{"Cold"},
		components:      []ComponentID{VerbalComponentID, SomaticComponentID},
		castingTime:     "1 standard action",
		spellRange:      "close (25 ft. + 5 ft./2 levels)",
		targetEffect:    "ray",
		duration:        "instantaneous",
		savingThrow:     "none",
		spellResistance: "yes",
	},
	{
		id:              SpellID("Read Magic"),
		school:          DivinationSchoolID,
		components:      []ComponentID{VerbalComponentID, SomaticComponentID, FocusComponentID},
		castingTime:     "1 standard action",
		spellRange:      "personal",
		targetEffect:    "you",
		duration:        "10 min./level",
		savingThrow:     "none",
		spellResistance: "no",
	},
	{
		id:              SpellID("Resistance"),
		school:          AbjurationSchoolID,
		components:      []ComponentID{VerbalComponentID, SomaticComponentID, MaterialComponentID, DivineFocusComponentID},
		castingTime:     "1 standard action",
		spellRange:      "touch",
		targetEffect:    "creature touched",
		duration:        "1 minute",
		savingThrow:     "Will negates (harmless)",
		spellResistance: "yes (harmless)",
	},
	{
		id:              SpellID("Stabilize"),
		school:          ConjurationSchoolID,
		components:      []ComponentID{VerbalComponentID, SomaticComponentID},
		castingTime:     "1 standard action",
		spellRange:      "close (25 ft. + 5 ft./2 levels)",
		targetEffect:    "one living creature",
		duration:        "instantaneous",
		savingThrow:     "Will negates (harmless)",
		spellResistance: "yes (harmless)",
	},
	{
		id:              SpellID("Summon Instrument"),
		school:          ConjurationSchoolID,
		components:      []ComponentID{VerbalComponentID, SomaticComponentID},
		castingTime:     "1 round",
		spellRange:      "0 ft.",
		targetEffect:    "one summoned handheld musical instrument",
		duration:        "1 min./level (D)",
		savingThrow:     "none",
		spellResistance: "no",
	},
	{
		id:              SpellID("Touch of Fatigue"),
		school:          NecromancySchoolID,
		components:      []ComponentID{VerbalComponentID, SomaticComponentID, MaterialComponentID},
		castingTime:     "1 standard action",
		spellRange:      "touch",
		targetEffect:    "creature touched",
		duration:        "1 round/level",
		savingThrow:     "Fortitude negates",
		spellResistance: "yes",
	},
	{
		id:              SpellID("Virtue"),
		school:          TransmutationSchoolID,
		components:      []ComponentID{VerbalComponentID, SomaticComponentID, DivineFocusComponentID},
		castingTime:     "1 standard action",
		spellRange:      "touch",
		targetEffect:    "creature touched",
		duration:        "1 min.",
		savingThrow:     "none",
		spellResistance: "yes (harmless)",
	},
}

func mustBuildCoreSpells(seeds []spellSeed) map[SpellID]Spell {
	spells := make(map[SpellID]Spell, len(seeds))

	for _, seed := range seeds {
		spell, ok := NewSpell(
			seed.id,
			seed.school,
			seed.descriptors,
			seed.components,
			seed.castingTime,
			seed.spellRange,
			seed.targetEffect,
			seed.duration,
			seed.savingThrow,
			seed.spellResistance,
		)
		if !ok {
			panic("invalid core spell seed")
		}

		if _, ok := spells[spell.GetID()]; ok {
			panic("duplicate core spell seed")
		}

		spells[spell.GetID()] = spell
	}

	return spells
}
