package spell

import characterclass "d20campaigngenerator/internal/domain/rpg/character/class"

type spellListEntrySeed struct {
	spellID    SpellID
	classID    characterclass.ClassID
	spellLevel int
}

var coreSpellListEntries = mustBuildCoreSpellListEntries(coreSpellListEntrySeeds)

var coreSpellListEntrySeeds = []spellListEntrySeed{
	{SpellID(`Dancing Lights`), characterclass.BardClassID, 0},
	{SpellID(`Daze`), characterclass.BardClassID, 0},
	{SpellID(`Detect Magic`), characterclass.BardClassID, 0},
	{SpellID(`Flare`), characterclass.BardClassID, 0},
	{SpellID(`Ghost Sound`), characterclass.BardClassID, 0},
	{SpellID(`Know Direction`), characterclass.BardClassID, 0},
	{SpellID(`Light`), characterclass.BardClassID, 0},
	{SpellID(`Lullaby`), characterclass.BardClassID, 0},
	{SpellID(`Mage Hand`), characterclass.BardClassID, 0},
	{SpellID(`Mending`), characterclass.BardClassID, 0},
	{SpellID(`Message`), characterclass.BardClassID, 0},
	{SpellID(`Open/Close`), characterclass.BardClassID, 0},
	{SpellID(`Prestidigitation`), characterclass.BardClassID, 0},
	{SpellID(`Read Magic`), characterclass.BardClassID, 0},
	{SpellID(`Resistance`), characterclass.BardClassID, 0},
	{SpellID(`Summon Instrument`), characterclass.BardClassID, 0},
	{SpellID(`Alarm`), characterclass.BardClassID, 1},
	{SpellID(`Animate Rope`), characterclass.BardClassID, 1},
	{SpellID(`Cause Fear`), characterclass.BardClassID, 1},
	{SpellID(`Charm Person`), characterclass.BardClassID, 1},
	{SpellID(`Comprehend Languages`), characterclass.BardClassID, 1},
	{SpellID(`Confusion, Lesser`), characterclass.BardClassID, 1},
	{SpellID(`Cure Light Wounds`), characterclass.BardClassID, 1},
	{SpellID(`Detect Secret Doors`), characterclass.BardClassID, 1},
	{SpellID(`Disguise Self`), characterclass.BardClassID, 1},
	{SpellID(`Erase`), characterclass.BardClassID, 1},
	{SpellID(`Expeditious Retreat`), characterclass.BardClassID, 1},
	{SpellID(`Feather Fall`), characterclass.BardClassID, 1},
	{SpellID(`Grease`), characterclass.BardClassID, 1},
	{SpellID(`Hideous Laughter`), characterclass.BardClassID, 1},
	{SpellID(`Hypnotism`), characterclass.BardClassID, 1},
	{SpellID(`Identify`), characterclass.BardClassID, 1},
	{SpellID(`Magic Aura`), characterclass.BardClassID, 1},
	{SpellID(`Magic Mouth`), characterclass.BardClassID, 1},
	{SpellID(`Obscure Object`), characterclass.BardClassID, 1},
	{SpellID(`Remove Fear`), characterclass.BardClassID, 1},
	{SpellID(`Silent Image`), characterclass.BardClassID, 1},
	{SpellID(`Sleep`), characterclass.BardClassID, 1},
	{SpellID(`Summon Monster 1`), characterclass.BardClassID, 1},
	{SpellID(`Undetectable Alignment`), characterclass.BardClassID, 1},
	{SpellID(`Unseen Servant`), characterclass.BardClassID, 1},
	{SpellID(`Ventriloquism`), characterclass.BardClassID, 1},
	{SpellID(`Alter Self`), characterclass.BardClassID, 2},
	{SpellID(`Animal Messenger`), characterclass.BardClassID, 2},
	{SpellID(`Animal Trance`), characterclass.BardClassID, 2},
	{SpellID(`Blindness/Deafness`), characterclass.BardClassID, 2},
	{SpellID(`Blur`), characterclass.BardClassID, 2},
	{SpellID(`Calm Emotions`), characterclass.BardClassID, 2},
	{SpellID(`Cat's Grace`), characterclass.BardClassID, 2},
	{SpellID(`Cure Moderate Wounds`), characterclass.BardClassID, 2},
	{SpellID(`Darkness`), characterclass.BardClassID, 2},
	{SpellID(`Daze Monster`), characterclass.BardClassID, 2},
	{SpellID(`Delay Poison`), characterclass.BardClassID, 2},
	{SpellID(`Detect Thoughts`), characterclass.BardClassID, 2},
	{SpellID(`Eagle's Splendor`), characterclass.BardClassID, 2},
	{SpellID(`Enthrall`), characterclass.BardClassID, 2},
	{SpellID(`Fox's Cunning`), characterclass.BardClassID, 2},
	{SpellID(`Glitterdust`), characterclass.BardClassID, 2},
	{SpellID(`Heroism`), characterclass.BardClassID, 2},
	{SpellID(`Hold Person`), characterclass.BardClassID, 2},
	{SpellID(`Hypnotic Pattern`), characterclass.BardClassID, 2},
	{SpellID(`Invisibility`), characterclass.BardClassID, 2},
	{SpellID(`Locate Object`), characterclass.BardClassID, 2},
	{SpellID(`Minor Image`), characterclass.BardClassID, 2},
	{SpellID(`Mirror Image`), characterclass.BardClassID, 2},
	{SpellID(`Misdirection`), characterclass.BardClassID, 2},
	{SpellID(`Pyrotechnics`), characterclass.BardClassID, 2},
	{SpellID(`Rage`), characterclass.BardClassID, 2},
	{SpellID(`Scare`), characterclass.BardClassID, 2},
	{SpellID(`Shatter`), characterclass.BardClassID, 2},
	{SpellID(`Silence`), characterclass.BardClassID, 2},
	{SpellID(`Sound Burst`), characterclass.BardClassID, 2},
	{SpellID(`Suggestion`), characterclass.BardClassID, 2},
	{SpellID(`Summon Monster 2`), characterclass.BardClassID, 2},
	{SpellID(`Summon Swarm`), characterclass.BardClassID, 2},
	{SpellID(`Tongues`), characterclass.BardClassID, 2},
	{SpellID(`Whispering Wind`), characterclass.BardClassID, 2},
	{SpellID(`Blink`), characterclass.BardClassID, 3},
	{SpellID(`Charm Monster`), characterclass.BardClassID, 3},
	{SpellID(`Clairaudience/Clairvoyance`), characterclass.BardClassID, 3},
	{SpellID(`Confusion`), characterclass.BardClassID, 3},
	{SpellID(`Crushing Despair`), characterclass.BardClassID, 3},
	{SpellID(`Cure Serious Wounds`), characterclass.BardClassID, 3},
	{SpellID(`Daylight`), characterclass.BardClassID, 3},
	{SpellID(`Deep Slumber`), characterclass.BardClassID, 3},
	{SpellID(`Dispel Magic`), characterclass.BardClassID, 3},
	{SpellID(`Displacement`), characterclass.BardClassID, 3},
	{SpellID(`Fear`), characterclass.BardClassID, 3},
	{SpellID(`Gaseous Form`), characterclass.BardClassID, 3},
	{SpellID(`Geas, Lesser`), characterclass.BardClassID, 3},
	{SpellID(`Glibness`), characterclass.BardClassID, 3},
	{SpellID(`Good Hope`), characterclass.BardClassID, 3},
	{SpellID(`Haste`), characterclass.BardClassID, 3},
	{SpellID(`Illusory Script`), characterclass.BardClassID, 3},
	{SpellID(`Invisibility Sphere`), characterclass.BardClassID, 3},
	{SpellID(`Major Image`), characterclass.BardClassID, 3},
	{SpellID(`Phantom Steed`), characterclass.BardClassID, 3},
	{SpellID(`Remove Curse`), characterclass.BardClassID, 3},
	{SpellID(`Scrying`), characterclass.BardClassID, 3},
	{SpellID(`Sculpt Sound`), characterclass.BardClassID, 3},
	{SpellID(`Secret Page`), characterclass.BardClassID, 3},
	{SpellID(`See Invisibility`), characterclass.BardClassID, 3},
	{SpellID(`Sepia Snake Sigil`), characterclass.BardClassID, 3},
	{SpellID(`Slow`), characterclass.BardClassID, 3},
	{SpellID(`Speak with Animals`), characterclass.BardClassID, 3},
	{SpellID(`Summon Monster 3`), characterclass.BardClassID, 3},
	{SpellID(`Tiny Hut`), characterclass.BardClassID, 3},
	{SpellID(`Break Enchantment`), characterclass.BardClassID, 4},
	{SpellID(`Cure Critical Wounds`), characterclass.BardClassID, 4},
	{SpellID(`Detect Scrying`), characterclass.BardClassID, 4},
	{SpellID(`Dimension Door`), characterclass.BardClassID, 4},
	{SpellID(`Dominate Person`), characterclass.BardClassID, 4},
	{SpellID(`Freedom of Movement`), characterclass.BardClassID, 4},
	{SpellID(`Hallucinatory Terrain`), characterclass.BardClassID, 4},
	{SpellID(`Hold Monster`), characterclass.BardClassID, 4},
	{SpellID(`Invisibility, Greater`), characterclass.BardClassID, 4},
	{SpellID(`Legend Lore`), characterclass.BardClassID, 4},
	{SpellID(`Locate Creature`), characterclass.BardClassID, 4},
	{SpellID(`Modify Memory`), characterclass.BardClassID, 4},
	{SpellID(`Neutralize Poison`), characterclass.BardClassID, 4},
	{SpellID(`Rainbow Pattern`), characterclass.BardClassID, 4},
	{SpellID(`Repel Vermin`), characterclass.BardClassID, 4},
	{SpellID(`Secure Shelter`), characterclass.BardClassID, 4},
	{SpellID(`Shadow Conjuration`), characterclass.BardClassID, 4},
	{SpellID(`Shout`), characterclass.BardClassID, 4},
	{SpellID(`Speak with Plants`), characterclass.BardClassID, 4},
	{SpellID(`Summon Monster 4`), characterclass.BardClassID, 4},
	{SpellID(`Zone of Silence`), characterclass.BardClassID, 4},
	{SpellID(`Cure Light Wounds, Mass`), characterclass.BardClassID, 5},
	{SpellID(`Dispel Magic, Greater`), characterclass.BardClassID, 5},
	{SpellID(`Dream`), characterclass.BardClassID, 5},
	{SpellID(`False Vision`), characterclass.BardClassID, 5},
	{SpellID(`Heroism, Greater`), characterclass.BardClassID, 5},
	{SpellID(`Mind Fog`), characterclass.BardClassID, 5},
	{SpellID(`Mirage Arcana`), characterclass.BardClassID, 5},
	{SpellID(`Mislead`), characterclass.BardClassID, 5},
	{SpellID(`Nightmare`), characterclass.BardClassID, 5},
	{SpellID(`Persistent Image`), characterclass.BardClassID, 5},
	{SpellID(`Seeming`), characterclass.BardClassID, 5},
	{SpellID(`Shadow Evocation`), characterclass.BardClassID, 5},
	{SpellID(`Shadow Walk`), characterclass.BardClassID, 5},
	{SpellID(`Song of Discord`), characterclass.BardClassID, 5},
	{SpellID(`Suggestion, Mass`), characterclass.BardClassID, 5},
	{SpellID(`Summon Monster 5`), characterclass.BardClassID, 5},
	{SpellID(`Analyze Dweomer`), characterclass.BardClassID, 6},
	{SpellID(`Animate Objects`), characterclass.BardClassID, 6},
	{SpellID(`Cat's Grace, Mass`), characterclass.BardClassID, 6},
	{SpellID(`Charm Monster, Mass`), characterclass.BardClassID, 6},
	{SpellID(`Cure Moderate Wounds, Mass`), characterclass.BardClassID, 6},
	{SpellID(`Eagle's Splendor, Mass`), characterclass.BardClassID, 6},
	{SpellID(`Eyebite`), characterclass.BardClassID, 6},
	{SpellID(`Find the Path`), characterclass.BardClassID, 6},
	{SpellID(`Fox's Cunning, Mass`), characterclass.BardClassID, 6},
	{SpellID(`Geas/Quest`), characterclass.BardClassID, 6},
	{SpellID(`Heroes' Feast`), characterclass.BardClassID, 6},
	{SpellID(`Irresistible Dance`), characterclass.BardClassID, 6},
	{SpellID(`Permanent Image`), characterclass.BardClassID, 6},
	{SpellID(`Programmed Image`), characterclass.BardClassID, 6},
	{SpellID(`Project Image`), characterclass.BardClassID, 6},
	{SpellID(`Scrying, Greater`), characterclass.BardClassID, 6},
	{SpellID(`Shout, Greater`), characterclass.BardClassID, 6},
	{SpellID(`Summon Monster 6`), characterclass.BardClassID, 6},
	{SpellID(`Sympathetic Vibration`), characterclass.BardClassID, 6},
	{SpellID(`Veil`), characterclass.BardClassID, 6},
	{SpellID(`Bleed`), characterclass.ClericClassID, 0},
	{SpellID(`Create Water`), characterclass.ClericClassID, 0},
	{SpellID(`Detect Magic`), characterclass.ClericClassID, 0},
	{SpellID(`Detect Poison`), characterclass.ClericClassID, 0},
	{SpellID(`Guidance`), characterclass.ClericClassID, 0},
	{SpellID(`Light`), characterclass.ClericClassID, 0},
	{SpellID(`Mending`), characterclass.ClericClassID, 0},
	{SpellID(`Purify Food and Drink`), characterclass.ClericClassID, 0},
	{SpellID(`Read Magic`), characterclass.ClericClassID, 0},
	{SpellID(`Resistance`), characterclass.ClericClassID, 0},
	{SpellID(`Stabilize`), characterclass.ClericClassID, 0},
	{SpellID(`Virtue`), characterclass.ClericClassID, 0},
	{SpellID(`Bane`), characterclass.ClericClassID, 1},
	{SpellID(`Bless`), characterclass.ClericClassID, 1},
	{SpellID(`Bless Water`), characterclass.ClericClassID, 1},
	{SpellID(`Cause Fear`), characterclass.ClericClassID, 1},
	{SpellID(`Command`), characterclass.ClericClassID, 1},
	{SpellID(`Comprehend Languages`), characterclass.ClericClassID, 1},
	{SpellID(`Cure Light Wounds`), characterclass.ClericClassID, 1},
	{SpellID(`Curse Water`), characterclass.ClericClassID, 1},
	{SpellID(`Deathwatch`), characterclass.ClericClassID, 1},
	{SpellID(`Detect Chaos`), characterclass.ClericClassID, 1},
	{SpellID(`Detect Evil`), characterclass.ClericClassID, 1},
	{SpellID(`Detect Good`), characterclass.ClericClassID, 1},
	{SpellID(`Detect Law`), characterclass.ClericClassID, 1},
	{SpellID(`Detect Undead`), characterclass.ClericClassID, 1},
	{SpellID(`Divine Favor`), characterclass.ClericClassID, 1},
	{SpellID(`Doom`), characterclass.ClericClassID, 1},
	{SpellID(`Endure Elements`), characterclass.ClericClassID, 1},
	{SpellID(`Entropic Shield`), characterclass.ClericClassID, 1},
	{SpellID(`Hide from Undead`), characterclass.ClericClassID, 1},
	{SpellID(`Inflict Light Wounds`), characterclass.ClericClassID, 1},
	{SpellID(`Magic Stone`), characterclass.ClericClassID, 1},
	{SpellID(`Magic Weapon`), characterclass.ClericClassID, 1},
	{SpellID(`Obscuring Mist`), characterclass.ClericClassID, 1},
	{SpellID(`Protection from Chaos`), characterclass.ClericClassID, 1},
	{SpellID(`Protection from Evil`), characterclass.ClericClassID, 1},
	{SpellID(`Protection from Good`), characterclass.ClericClassID, 1},
	{SpellID(`Protection from Law`), characterclass.ClericClassID, 1},
	{SpellID(`Remove Fear`), characterclass.ClericClassID, 1},
	{SpellID(`Sanctuary`), characterclass.ClericClassID, 1},
	{SpellID(`Shield of Faith`), characterclass.ClericClassID, 1},
	{SpellID(`Summon Monster 1`), characterclass.ClericClassID, 1},
	{SpellID(`Aid`), characterclass.ClericClassID, 2},
	{SpellID(`Align Weapon`), characterclass.ClericClassID, 2},
	{SpellID(`Augury`), characterclass.ClericClassID, 2},
	{SpellID(`Bear's Endurance`), characterclass.ClericClassID, 2},
	{SpellID(`Bull's Strength`), characterclass.ClericClassID, 2},
	{SpellID(`Calm Emotions`), characterclass.ClericClassID, 2},
	{SpellID(`Consecrate`), characterclass.ClericClassID, 2},
	{SpellID(`Cure Moderate Wounds`), characterclass.ClericClassID, 2},
	{SpellID(`Darkness`), characterclass.ClericClassID, 2},
	{SpellID(`Death Knell`), characterclass.ClericClassID, 2},
	{SpellID(`Delay Poison`), characterclass.ClericClassID, 2},
	{SpellID(`Desecrate`), characterclass.ClericClassID, 2},
	{SpellID(`Eagle's Splendor`), characterclass.ClericClassID, 2},
	{SpellID(`Enthrall`), characterclass.ClericClassID, 2},
	{SpellID(`Find Traps`), characterclass.ClericClassID, 2},
	{SpellID(`Gentle Repose`), characterclass.ClericClassID, 2},
	{SpellID(`Hold Person`), characterclass.ClericClassID, 2},
	{SpellID(`Inflict Moderate Wounds`), characterclass.ClericClassID, 2},
	{SpellID(`Make Whole`), characterclass.ClericClassID, 2},
	{SpellID(`Owl's Wisdom`), characterclass.ClericClassID, 2},
	{SpellID(`Remove Paralysis`), characterclass.ClericClassID, 2},
	{SpellID(`Resist Energy`), characterclass.ClericClassID, 2},
	{SpellID(`Restoration, Lesser`), characterclass.ClericClassID, 2},
	{SpellID(`Shatter`), characterclass.ClericClassID, 2},
	{SpellID(`Shield Other`), characterclass.ClericClassID, 2},
	{SpellID(`Silence`), characterclass.ClericClassID, 2},
	{SpellID(`Sound Burst`), characterclass.ClericClassID, 2},
	{SpellID(`Spiritual Weapon`), characterclass.ClericClassID, 2},
	{SpellID(`Status`), characterclass.ClericClassID, 2},
	{SpellID(`Summon Monster 2`), characterclass.ClericClassID, 2},
	{SpellID(`Undetectable Alignment`), characterclass.ClericClassID, 2},
	{SpellID(`Zone of Truth`), characterclass.ClericClassID, 2},
	{SpellID(`Animate Dead`), characterclass.ClericClassID, 3},
	{SpellID(`Bestow Curse`), characterclass.ClericClassID, 3},
	{SpellID(`Blindness/Deafness`), characterclass.ClericClassID, 3},
	{SpellID(`Contagion`), characterclass.ClericClassID, 3},
	{SpellID(`Continual Flame`), characterclass.ClericClassID, 3},
	{SpellID(`Create Food and Water`), characterclass.ClericClassID, 3},
	{SpellID(`Cure Serious Wounds`), characterclass.ClericClassID, 3},
	{SpellID(`Daylight`), characterclass.ClericClassID, 3},
	{SpellID(`Deeper Darkness`), characterclass.ClericClassID, 3},
	{SpellID(`Dispel Magic`), characterclass.ClericClassID, 3},
	{SpellID(`Glyph of Warding`), characterclass.ClericClassID, 3},
	{SpellID(`Helping Hand`), characterclass.ClericClassID, 3},
	{SpellID(`Inflict Serious Wounds`), characterclass.ClericClassID, 3},
	{SpellID(`Invisibility Purge`), characterclass.ClericClassID, 3},
	{SpellID(`Locate Object`), characterclass.ClericClassID, 3},
	{SpellID(`Magic Circle against Chaos`), characterclass.ClericClassID, 3},
	{SpellID(`Magic Circle against Evil`), characterclass.ClericClassID, 3},
	{SpellID(`Magic Circle against Good`), characterclass.ClericClassID, 3},
	{SpellID(`Magic Circle against Law`), characterclass.ClericClassID, 3},
	{SpellID(`Magic Vestment`), characterclass.ClericClassID, 3},
	{SpellID(`Meld into Stone`), characterclass.ClericClassID, 3},
	{SpellID(`Obscure Object`), characterclass.ClericClassID, 3},
	{SpellID(`Prayer`), characterclass.ClericClassID, 3},
	{SpellID(`Protection from Energy`), characterclass.ClericClassID, 3},
	{SpellID(`Remove Blindness/Deafness`), characterclass.ClericClassID, 3},
	{SpellID(`Remove Curse`), characterclass.ClericClassID, 3},
	{SpellID(`Remove Disease`), characterclass.ClericClassID, 3},
	{SpellID(`Searing Light`), characterclass.ClericClassID, 3},
	{SpellID(`Speak with Dead`), characterclass.ClericClassID, 3},
	{SpellID(`Stone Shape`), characterclass.ClericClassID, 3},
	{SpellID(`Summon Monster 3`), characterclass.ClericClassID, 3},
	{SpellID(`Water Breathing`), characterclass.ClericClassID, 3},
	{SpellID(`Water Walk`), characterclass.ClericClassID, 3},
	{SpellID(`Wind Wall`), characterclass.ClericClassID, 3},
	{SpellID(`Air Walk`), characterclass.ClericClassID, 4},
	{SpellID(`Chaos Hammer`), characterclass.ClericClassID, 4},
	{SpellID(`Control Water`), characterclass.ClericClassID, 4},
	{SpellID(`Cure Critical Wounds`), characterclass.ClericClassID, 4},
	{SpellID(`Death Ward`), characterclass.ClericClassID, 4},
	{SpellID(`Dimensional Anchor`), characterclass.ClericClassID, 4},
	{SpellID(`Discern Lies`), characterclass.ClericClassID, 4},
	{SpellID(`Dismissal`), characterclass.ClericClassID, 4},
	{SpellID(`Divination`), characterclass.ClericClassID, 4},
	{SpellID(`Divine Power`), characterclass.ClericClassID, 4},
	{SpellID(`Freedom of Movement`), characterclass.ClericClassID, 4},
	{SpellID(`Giant Vermin`), characterclass.ClericClassID, 4},
	{SpellID(`Holy Smite`), characterclass.ClericClassID, 4},
	{SpellID(`Imbue with Spell Ability`), characterclass.ClericClassID, 4},
	{SpellID(`Inflict Critical Wounds`), characterclass.ClericClassID, 4},
	{SpellID(`Magic Weapon, Greater`), characterclass.ClericClassID, 4},
	{SpellID(`Neutralize Poison`), characterclass.ClericClassID, 4},
	{SpellID(`Order's Wrath`), characterclass.ClericClassID, 4},
	{SpellID(`Planar Ally, Lesser`), characterclass.ClericClassID, 4},
	{SpellID(`Poison`), characterclass.ClericClassID, 4},
	{SpellID(`Repel Vermin`), characterclass.ClericClassID, 4},
	{SpellID(`Restoration`), characterclass.ClericClassID, 4},
	{SpellID(`Sending`), characterclass.ClericClassID, 4},
	{SpellID(`Spell Immunity`), characterclass.ClericClassID, 4},
	{SpellID(`Summon Monster 4`), characterclass.ClericClassID, 4},
	{SpellID(`Tongues`), characterclass.ClericClassID, 4},
	{SpellID(`Unholy Blight`), characterclass.ClericClassID, 4},
	{SpellID(`Atonement`), characterclass.ClericClassID, 5},
	{SpellID(`Break Enchantment`), characterclass.ClericClassID, 5},
	{SpellID(`Breath of Life`), characterclass.ClericClassID, 5},
	{SpellID(`Command, Greater`), characterclass.ClericClassID, 5},
	{SpellID(`Commune`), characterclass.ClericClassID, 5},
	{SpellID(`Cure Light Wounds, Mass`), characterclass.ClericClassID, 5},
	{SpellID(`Dispel Chaos`), characterclass.ClericClassID, 5},
	{SpellID(`Dispel Evil`), characterclass.ClericClassID, 5},
	{SpellID(`Dispel Good`), characterclass.ClericClassID, 5},
	{SpellID(`Dispel Law`), characterclass.ClericClassID, 5},
	{SpellID(`Disrupting Weapon`), characterclass.ClericClassID, 5},
	{SpellID(`Flame Strike`), characterclass.ClericClassID, 5},
	{SpellID(`Hallow`), characterclass.ClericClassID, 5},
	{SpellID(`Inflict Light Wounds, Mass`), characterclass.ClericClassID, 5},
	{SpellID(`Insect Plague`), characterclass.ClericClassID, 5},
	{SpellID(`Mark of Justice`), characterclass.ClericClassID, 5},
	{SpellID(`Plane Shift`), characterclass.ClericClassID, 5},
	{SpellID(`Raise Dead`), characterclass.ClericClassID, 5},
	{SpellID(`Righteous Might`), characterclass.ClericClassID, 5},
	{SpellID(`Scrying`), characterclass.ClericClassID, 5},
	{SpellID(`Slay Living`), characterclass.ClericClassID, 5},
	{SpellID(`Spell Resistance`), characterclass.ClericClassID, 5},
	{SpellID(`Summon Monster 5`), characterclass.ClericClassID, 5},
	{SpellID(`Symbol of Pain`), characterclass.ClericClassID, 5},
	{SpellID(`Symbol of Sleep`), characterclass.ClericClassID, 5},
	{SpellID(`True Seeing`), characterclass.ClericClassID, 5},
	{SpellID(`Unhallow`), characterclass.ClericClassID, 5},
	{SpellID(`Wall of Stone`), characterclass.ClericClassID, 5},
	{SpellID(`Animate Objects`), characterclass.ClericClassID, 6},
	{SpellID(`Antilife Shell`), characterclass.ClericClassID, 6},
	{SpellID(`Banishment`), characterclass.ClericClassID, 6},
	{SpellID(`Bear's Endurance, Mass`), characterclass.ClericClassID, 6},
	{SpellID(`Blade Barrier`), characterclass.ClericClassID, 6},
	{SpellID(`Bull's Strength, Mass`), characterclass.ClericClassID, 6},
	{SpellID(`Create Undead`), characterclass.ClericClassID, 6},
	{SpellID(`Cure Moderate Wounds, Mass`), characterclass.ClericClassID, 6},
	{SpellID(`Dispel Magic, Greater`), characterclass.ClericClassID, 6},
	{SpellID(`Eagle's Splendor, Mass`), characterclass.ClericClassID, 6},
	{SpellID(`Find the Path`), characterclass.ClericClassID, 6},
	{SpellID(`Forbiddance`), characterclass.ClericClassID, 6},
	{SpellID(`Geas/Quest`), characterclass.ClericClassID, 6},
	{SpellID(`Glyph of Warding, Greater`), characterclass.ClericClassID, 6},
	{SpellID(`Harm`), characterclass.ClericClassID, 6},
	{SpellID(`Heal`), characterclass.ClericClassID, 6},
	{SpellID(`Heroes' Feast`), characterclass.ClericClassID, 6},
	{SpellID(`Inflict Moderate Wounds, Mass`), characterclass.ClericClassID, 6},
	{SpellID(`Owl's Wisdom, Mass`), characterclass.ClericClassID, 6},
	{SpellID(`Planar Ally`), characterclass.ClericClassID, 6},
	{SpellID(`Summon Monster 6`), characterclass.ClericClassID, 6},
	{SpellID(`Symbol of Fear`), characterclass.ClericClassID, 6},
	{SpellID(`Symbol of Persuasion`), characterclass.ClericClassID, 6},
	{SpellID(`Undeath to Death`), characterclass.ClericClassID, 6},
	{SpellID(`Wind Walk`), characterclass.ClericClassID, 6},
	{SpellID(`Word of Recall`), characterclass.ClericClassID, 6},
	{SpellID(`Blasphemy`), characterclass.ClericClassID, 7},
	{SpellID(`Control Weather`), characterclass.ClericClassID, 7},
	{SpellID(`Cure Serious Wounds, Mass`), characterclass.ClericClassID, 7},
	{SpellID(`Destruction`), characterclass.ClericClassID, 7},
	{SpellID(`Dictum`), characterclass.ClericClassID, 7},
	{SpellID(`Ethereal Jaunt`), characterclass.ClericClassID, 7},
	{SpellID(`Holy Word`), characterclass.ClericClassID, 7},
	{SpellID(`Inflict Serious Wounds, Mass`), characterclass.ClericClassID, 7},
	{SpellID(`Refuge`), characterclass.ClericClassID, 7},
	{SpellID(`Regenerate`), characterclass.ClericClassID, 7},
	{SpellID(`Repulsion`), characterclass.ClericClassID, 7},
	{SpellID(`Restoration, Greater`), characterclass.ClericClassID, 7},
	{SpellID(`Resurrection`), characterclass.ClericClassID, 7},
	{SpellID(`Scrying, Greater`), characterclass.ClericClassID, 7},
	{SpellID(`Summon Monster 7`), characterclass.ClericClassID, 7},
	{SpellID(`Symbol of Stunning`), characterclass.ClericClassID, 7},
	{SpellID(`Symbol of Weakness`), characterclass.ClericClassID, 7},
	{SpellID(`Word of Chaos`), characterclass.ClericClassID, 7},
	{SpellID(`Antimagic Field`), characterclass.ClericClassID, 8},
	{SpellID(`Cloak of Chaos`), characterclass.ClericClassID, 8},
	{SpellID(`Create Greater Undead`), characterclass.ClericClassID, 8},
	{SpellID(`Cure Critical Wounds, Mass`), characterclass.ClericClassID, 8},
	{SpellID(`Dimensional Lock`), characterclass.ClericClassID, 8},
	{SpellID(`Discern Location`), characterclass.ClericClassID, 8},
	{SpellID(`Earthquake`), characterclass.ClericClassID, 8},
	{SpellID(`Fire Storm`), characterclass.ClericClassID, 8},
	{SpellID(`Holy Aura`), characterclass.ClericClassID, 8},
	{SpellID(`Inflict Critical Wounds, Mass`), characterclass.ClericClassID, 8},
	{SpellID(`Planar Ally, Greater`), characterclass.ClericClassID, 8},
	{SpellID(`Shield of Law`), characterclass.ClericClassID, 8},
	{SpellID(`Spell Immunity, Greater`), characterclass.ClericClassID, 8},
	{SpellID(`Summon Monster 8`), characterclass.ClericClassID, 8},
	{SpellID(`Symbol of Death`), characterclass.ClericClassID, 8},
	{SpellID(`Symbol of Insanity`), characterclass.ClericClassID, 8},
	{SpellID(`Unholy Aura`), characterclass.ClericClassID, 8},
	{SpellID(`Astral Projection`), characterclass.ClericClassID, 9},
	{SpellID(`Energy Drain`), characterclass.ClericClassID, 9},
	{SpellID(`Etherealness`), characterclass.ClericClassID, 9},
	{SpellID(`Gate`), characterclass.ClericClassID, 9},
	{SpellID(`Heal, Mass`), characterclass.ClericClassID, 9},
	{SpellID(`Implosion`), characterclass.ClericClassID, 9},
	{SpellID(`Miracle`), characterclass.ClericClassID, 9},
	{SpellID(`Soul Bind`), characterclass.ClericClassID, 9},
	{SpellID(`Storm of Vengeance`), characterclass.ClericClassID, 9},
	{SpellID(`Summon Monster 9`), characterclass.ClericClassID, 9},
	{SpellID(`True Resurrection`), characterclass.ClericClassID, 9},
	{SpellID(`Create Water`), characterclass.DruidClassID, 0},
	{SpellID(`Detect Magic`), characterclass.DruidClassID, 0},
	{SpellID(`Detect Poison`), characterclass.DruidClassID, 0},
	{SpellID(`Flare`), characterclass.DruidClassID, 0},
	{SpellID(`Guidance`), characterclass.DruidClassID, 0},
	{SpellID(`Know Direction`), characterclass.DruidClassID, 0},
	{SpellID(`Light`), characterclass.DruidClassID, 0},
	{SpellID(`Mending`), characterclass.DruidClassID, 0},
	{SpellID(`Purify Food and Drink`), characterclass.DruidClassID, 0},
	{SpellID(`Read Magic`), characterclass.DruidClassID, 0},
	{SpellID(`Resistance`), characterclass.DruidClassID, 0},
	{SpellID(`Stabilize`), characterclass.DruidClassID, 0},
	{SpellID(`Virtue`), characterclass.DruidClassID, 0},
	{SpellID(`Calm Animals`), characterclass.DruidClassID, 1},
	{SpellID(`Charm Animal`), characterclass.DruidClassID, 1},
	{SpellID(`Cure Light Wounds`), characterclass.DruidClassID, 1},
	{SpellID(`Detect Animals or Plants`), characterclass.DruidClassID, 1},
	{SpellID(`Detect Snares and Pits`), characterclass.DruidClassID, 1},
	{SpellID(`Endure Elements`), characterclass.DruidClassID, 1},
	{SpellID(`Entangle`), characterclass.DruidClassID, 1},
	{SpellID(`Faerie Fire`), characterclass.DruidClassID, 1},
	{SpellID(`Goodberry`), characterclass.DruidClassID, 1},
	{SpellID(`Hide from Animals`), characterclass.DruidClassID, 1},
	{SpellID(`Jump`), characterclass.DruidClassID, 1},
	{SpellID(`Longstrider`), characterclass.DruidClassID, 1},
	{SpellID(`Magic Fang`), characterclass.DruidClassID, 1},
	{SpellID(`Magic Stone`), characterclass.DruidClassID, 1},
	{SpellID(`Obscuring Mist`), characterclass.DruidClassID, 1},
	{SpellID(`Pass without Trace`), characterclass.DruidClassID, 1},
	{SpellID(`Produce Flame`), characterclass.DruidClassID, 1},
	{SpellID(`Shillelagh`), characterclass.DruidClassID, 1},
	{SpellID(`Speak with Animals`), characterclass.DruidClassID, 1},
	{SpellID(`Summon Nature's Ally 1`), characterclass.DruidClassID, 1},
	{SpellID(`Animal Messenger`), characterclass.DruidClassID, 2},
	{SpellID(`Animal Trance`), characterclass.DruidClassID, 2},
	{SpellID(`Barkskin`), characterclass.DruidClassID, 2},
	{SpellID(`Bear's Endurance`), characterclass.DruidClassID, 2},
	{SpellID(`Bull's Strength`), characterclass.DruidClassID, 2},
	{SpellID(`Cat's Grace`), characterclass.DruidClassID, 2},
	{SpellID(`Chill Metal`), characterclass.DruidClassID, 2},
	{SpellID(`Delay Poison`), characterclass.DruidClassID, 2},
	{SpellID(`Fire Trap`), characterclass.DruidClassID, 2},
	{SpellID(`Flame Blade`), characterclass.DruidClassID, 2},
	{SpellID(`Flaming Sphere`), characterclass.DruidClassID, 2},
	{SpellID(`Fog Cloud`), characterclass.DruidClassID, 2},
	{SpellID(`Gust of Wind`), characterclass.DruidClassID, 2},
	{SpellID(`Heat Metal`), characterclass.DruidClassID, 2},
	{SpellID(`Hold Animal`), characterclass.DruidClassID, 2},
	{SpellID(`Owl's Wisdom`), characterclass.DruidClassID, 2},
	{SpellID(`Reduce Animal`), characterclass.DruidClassID, 2},
	{SpellID(`Resist Energy`), characterclass.DruidClassID, 2},
	{SpellID(`Restoration, Lesser`), characterclass.DruidClassID, 2},
	{SpellID(`Soften Earth and Stone`), characterclass.DruidClassID, 2},
	{SpellID(`Spider Climb`), characterclass.DruidClassID, 2},
	{SpellID(`Summon Nature's Ally 2`), characterclass.DruidClassID, 2},
	{SpellID(`Summon Swarm`), characterclass.DruidClassID, 2},
	{SpellID(`Tree Shape`), characterclass.DruidClassID, 2},
	{SpellID(`Warp Wood`), characterclass.DruidClassID, 2},
	{SpellID(`Wood Shape`), characterclass.DruidClassID, 2},
	{SpellID(`Call Lightning`), characterclass.DruidClassID, 3},
	{SpellID(`Contagion`), characterclass.DruidClassID, 3},
	{SpellID(`Cure Moderate Wounds`), characterclass.DruidClassID, 3},
	{SpellID(`Daylight`), characterclass.DruidClassID, 3},
	{SpellID(`Diminish Plants`), characterclass.DruidClassID, 3},
	{SpellID(`Dominate Animal`), characterclass.DruidClassID, 3},
	{SpellID(`Magic Fang, Greater`), characterclass.DruidClassID, 3},
	{SpellID(`Meld into Stone`), characterclass.DruidClassID, 3},
	{SpellID(`Neutralize Poison`), characterclass.DruidClassID, 3},
	{SpellID(`Plant Growth`), characterclass.DruidClassID, 3},
	{SpellID(`Poison`), characterclass.DruidClassID, 3},
	{SpellID(`Protection from Energy`), characterclass.DruidClassID, 3},
	{SpellID(`Quench`), characterclass.DruidClassID, 3},
	{SpellID(`Remove Disease`), characterclass.DruidClassID, 3},
	{SpellID(`Sleet Storm`), characterclass.DruidClassID, 3},
	{SpellID(`Snare`), characterclass.DruidClassID, 3},
	{SpellID(`Speak with Plants`), characterclass.DruidClassID, 3},
	{SpellID(`Spike Growth`), characterclass.DruidClassID, 3},
	{SpellID(`Stone Shape`), characterclass.DruidClassID, 3},
	{SpellID(`Summon Nature's Ally 3`), characterclass.DruidClassID, 3},
	{SpellID(`Water Breathing`), characterclass.DruidClassID, 3},
	{SpellID(`Wind Wall`), characterclass.DruidClassID, 3},
	{SpellID(`Air Walk`), characterclass.DruidClassID, 4},
	{SpellID(`Antiplant Shell`), characterclass.DruidClassID, 4},
	{SpellID(`Blight`), characterclass.DruidClassID, 4},
	{SpellID(`Command Plants`), characterclass.DruidClassID, 4},
	{SpellID(`Control Water`), characterclass.DruidClassID, 4},
	{SpellID(`Cure Serious Wounds`), characterclass.DruidClassID, 4},
	{SpellID(`Dispel Magic`), characterclass.DruidClassID, 4},
	{SpellID(`Flame Strike`), characterclass.DruidClassID, 4},
	{SpellID(`Freedom of Movement`), characterclass.DruidClassID, 4},
	{SpellID(`Giant Vermin`), characterclass.DruidClassID, 4},
	{SpellID(`Ice Storm`), characterclass.DruidClassID, 4},
	{SpellID(`Reincarnate`), characterclass.DruidClassID, 4},
	{SpellID(`Repel Vermin`), characterclass.DruidClassID, 4},
	{SpellID(`Rusting Grasp`), characterclass.DruidClassID, 4},
	{SpellID(`Scrying`), characterclass.DruidClassID, 4},
	{SpellID(`Spike Stones`), characterclass.DruidClassID, 4},
	{SpellID(`Summon Nature's Ally 4`), characterclass.DruidClassID, 4},
	{SpellID(`Animal Growth`), characterclass.DruidClassID, 5},
	{SpellID(`Atonement`), characterclass.DruidClassID, 5},
	{SpellID(`Awaken`), characterclass.DruidClassID, 5},
	{SpellID(`Baleful Polymorph`), characterclass.DruidClassID, 5},
	{SpellID(`Call Lightning Storm`), characterclass.DruidClassID, 5},
	{SpellID(`Commune with Nature`), characterclass.DruidClassID, 5},
	{SpellID(`Control Winds`), characterclass.DruidClassID, 5},
	{SpellID(`Cure Critical Wounds`), characterclass.DruidClassID, 5},
	{SpellID(`Death Ward`), characterclass.DruidClassID, 5},
	{SpellID(`Hallow`), characterclass.DruidClassID, 5},
	{SpellID(`Insect Plague`), characterclass.DruidClassID, 5},
	{SpellID(`Stoneskin`), characterclass.DruidClassID, 5},
	{SpellID(`Summon Nature's Ally 5`), characterclass.DruidClassID, 5},
	{SpellID(`Transmute Mud to Rock`), characterclass.DruidClassID, 5},
	{SpellID(`Transmute Rock to Mud`), characterclass.DruidClassID, 5},
	{SpellID(`Tree Stride`), characterclass.DruidClassID, 5},
	{SpellID(`Unhallow`), characterclass.DruidClassID, 5},
	{SpellID(`Wall of Fire`), characterclass.DruidClassID, 5},
	{SpellID(`Wall of Thorns`), characterclass.DruidClassID, 5},
	{SpellID(`Antilife Shell`), characterclass.DruidClassID, 6},
	{SpellID(`Bear's Endurance, Mass`), characterclass.DruidClassID, 6},
	{SpellID(`Bull's Strength, Mass`), characterclass.DruidClassID, 6},
	{SpellID(`Cat's Grace, Mass`), characterclass.DruidClassID, 6},
	{SpellID(`Cure Light Wounds, Mass`), characterclass.DruidClassID, 6},
	{SpellID(`Dispel Magic, Greater`), characterclass.DruidClassID, 6},
	{SpellID(`Find the Path`), characterclass.DruidClassID, 6},
	{SpellID(`Fire Seeds`), characterclass.DruidClassID, 6},
	{SpellID(`Ironwood`), characterclass.DruidClassID, 6},
	{SpellID(`Liveoak`), characterclass.DruidClassID, 6},
	{SpellID(`Move Earth`), characterclass.DruidClassID, 6},
	{SpellID(`Owl's Wisdom, Mass`), characterclass.DruidClassID, 6},
	{SpellID(`Repel Wood`), characterclass.DruidClassID, 6},
	{SpellID(`Spellstaff`), characterclass.DruidClassID, 6},
	{SpellID(`Stone Tell`), characterclass.DruidClassID, 6},
	{SpellID(`Summon Nature's Ally 6`), characterclass.DruidClassID, 6},
	{SpellID(`Transport via Plants`), characterclass.DruidClassID, 6},
	{SpellID(`Wall of Stone`), characterclass.DruidClassID, 6},
	{SpellID(`Animate Plants`), characterclass.DruidClassID, 7},
	{SpellID(`Changestaff`), characterclass.DruidClassID, 7},
	{SpellID(`Control Weather`), characterclass.DruidClassID, 7},
	{SpellID(`Creeping Doom`), characterclass.DruidClassID, 7},
	{SpellID(`Cure Moderate Wounds, Mass`), characterclass.DruidClassID, 7},
	{SpellID(`Fire Storm`), characterclass.DruidClassID, 7},
	{SpellID(`Heal`), characterclass.DruidClassID, 7},
	{SpellID(`Scrying, Greater`), characterclass.DruidClassID, 7},
	{SpellID(`Summon Nature's Ally 7`), characterclass.DruidClassID, 7},
	{SpellID(`Sunbeam`), characterclass.DruidClassID, 7},
	{SpellID(`Transmute Metal to Wood`), characterclass.DruidClassID, 7},
	{SpellID(`True Seeing`), characterclass.DruidClassID, 7},
	{SpellID(`Wind Walk`), characterclass.DruidClassID, 7},
	{SpellID(`Animal Shapes`), characterclass.DruidClassID, 8},
	{SpellID(`Control Plants`), characterclass.DruidClassID, 8},
	{SpellID(`Cure Serious Wounds, Mass`), characterclass.DruidClassID, 8},
	{SpellID(`Earthquake`), characterclass.DruidClassID, 8},
	{SpellID(`Finger of Death`), characterclass.DruidClassID, 8},
	{SpellID(`Repel Metal or Stone`), characterclass.DruidClassID, 8},
	{SpellID(`Reverse Gravity`), characterclass.DruidClassID, 8},
	{SpellID(`Summon Nature's Ally 8`), characterclass.DruidClassID, 8},
	{SpellID(`Sunburst`), characterclass.DruidClassID, 8},
	{SpellID(`Whirlwind`), characterclass.DruidClassID, 8},
	{SpellID(`Word of Recall`), characterclass.DruidClassID, 8},
	{SpellID(`Antipathy`), characterclass.DruidClassID, 9},
	{SpellID(`Cure Critical Wounds, Mass`), characterclass.DruidClassID, 9},
	{SpellID(`Elemental Swarm`), characterclass.DruidClassID, 9},
	{SpellID(`Foresight`), characterclass.DruidClassID, 9},
	{SpellID(`Regenerate`), characterclass.DruidClassID, 9},
	{SpellID(`Shambler`), characterclass.DruidClassID, 9},
	{SpellID(`Shapechange`), characterclass.DruidClassID, 9},
	{SpellID(`Storm of Vengeance`), characterclass.DruidClassID, 9},
	{SpellID(`Summon Nature's Ally 9`), characterclass.DruidClassID, 9},
	{SpellID(`Sympathy`), characterclass.DruidClassID, 9},
	{SpellID(`Bless`), characterclass.PaladinClassID, 1},
	{SpellID(`Bless Water`), characterclass.PaladinClassID, 1},
	{SpellID(`Bless Weapon`), characterclass.PaladinClassID, 1},
	{SpellID(`Create Water`), characterclass.PaladinClassID, 1},
	{SpellID(`Cure Light Wounds`), characterclass.PaladinClassID, 1},
	{SpellID(`Detect Poison`), characterclass.PaladinClassID, 1},
	{SpellID(`Detect Undead`), characterclass.PaladinClassID, 1},
	{SpellID(`Divine Favor`), characterclass.PaladinClassID, 1},
	{SpellID(`Endure Elements`), characterclass.PaladinClassID, 1},
	{SpellID(`Magic Weapon`), characterclass.PaladinClassID, 1},
	{SpellID(`Protection from Chaos`), characterclass.PaladinClassID, 1},
	{SpellID(`Protection from Evil`), characterclass.PaladinClassID, 1},
	{SpellID(`Read Magic`), characterclass.PaladinClassID, 1},
	{SpellID(`Resistance`), characterclass.PaladinClassID, 1},
	{SpellID(`Restoration, Lesser`), characterclass.PaladinClassID, 1},
	{SpellID(`Virtue`), characterclass.PaladinClassID, 1},
	{SpellID(`Bull's Strength`), characterclass.PaladinClassID, 2},
	{SpellID(`Delay Poison`), characterclass.PaladinClassID, 2},
	{SpellID(`Eagle's Splendor`), characterclass.PaladinClassID, 2},
	{SpellID(`Owl's Wisdom`), characterclass.PaladinClassID, 2},
	{SpellID(`Remove Paralysis`), characterclass.PaladinClassID, 2},
	{SpellID(`Resist Energy`), characterclass.PaladinClassID, 2},
	{SpellID(`Shield Other`), characterclass.PaladinClassID, 2},
	{SpellID(`Undetectable Alignment`), characterclass.PaladinClassID, 2},
	{SpellID(`Zone of Truth`), characterclass.PaladinClassID, 2},
	{SpellID(`Cure Moderate Wounds`), characterclass.PaladinClassID, 3},
	{SpellID(`Daylight`), characterclass.PaladinClassID, 3},
	{SpellID(`Discern Lies`), characterclass.PaladinClassID, 3},
	{SpellID(`Dispel Magic`), characterclass.PaladinClassID, 3},
	{SpellID(`Heal Mount`), characterclass.PaladinClassID, 3},
	{SpellID(`Magic Circle against Chaos`), characterclass.PaladinClassID, 3},
	{SpellID(`Magic Circle against Evil`), characterclass.PaladinClassID, 3},
	{SpellID(`Magic Weapon, Greater`), characterclass.PaladinClassID, 3},
	{SpellID(`Prayer`), characterclass.PaladinClassID, 3},
	{SpellID(`Remove Blindness/Deafness`), characterclass.PaladinClassID, 3},
	{SpellID(`Remove Curse`), characterclass.PaladinClassID, 3},
	{SpellID(`Break Enchantment`), characterclass.PaladinClassID, 4},
	{SpellID(`Cure Serious Wounds`), characterclass.PaladinClassID, 4},
	{SpellID(`Death Ward`), characterclass.PaladinClassID, 4},
	{SpellID(`Dispel Chaos`), characterclass.PaladinClassID, 4},
	{SpellID(`Dispel Evil`), characterclass.PaladinClassID, 4},
	{SpellID(`Holy Sword`), characterclass.PaladinClassID, 4},
	{SpellID(`Mark of Justice`), characterclass.PaladinClassID, 4},
	{SpellID(`Neutralize Poison`), characterclass.PaladinClassID, 4},
	{SpellID(`Restoration`), characterclass.PaladinClassID, 4},
	{SpellID(`Alarm`), characterclass.RangerClassID, 1},
	{SpellID(`Animal Messenger`), characterclass.RangerClassID, 1},
	{SpellID(`Calm Animals`), characterclass.RangerClassID, 1},
	{SpellID(`Charm Animal`), characterclass.RangerClassID, 1},
	{SpellID(`Delay Poison`), characterclass.RangerClassID, 1},
	{SpellID(`Detect Animals or Plants`), characterclass.RangerClassID, 1},
	{SpellID(`Detect Poison`), characterclass.RangerClassID, 1},
	{SpellID(`Detect Snares and Pits`), characterclass.RangerClassID, 1},
	{SpellID(`Endure Elements`), characterclass.RangerClassID, 1},
	{SpellID(`Entangle`), characterclass.RangerClassID, 1},
	{SpellID(`Hide from Animals`), characterclass.RangerClassID, 1},
	{SpellID(`Jump`), characterclass.RangerClassID, 1},
	{SpellID(`Longstrider`), characterclass.RangerClassID, 1},
	{SpellID(`Magic Fang`), characterclass.RangerClassID, 1},
	{SpellID(`Pass without Trace`), characterclass.RangerClassID, 1},
	{SpellID(`Read Magic`), characterclass.RangerClassID, 1},
	{SpellID(`Resist Energy`), characterclass.RangerClassID, 1},
	{SpellID(`Speak with Animals`), characterclass.RangerClassID, 1},
	{SpellID(`Summon Nature's Ally 1`), characterclass.RangerClassID, 1},
	{SpellID(`Barkskin`), characterclass.RangerClassID, 2},
	{SpellID(`Bear's Endurance`), characterclass.RangerClassID, 2},
	{SpellID(`Cat's Grace`), characterclass.RangerClassID, 2},
	{SpellID(`Cure Light Wounds`), characterclass.RangerClassID, 2},
	{SpellID(`Hold Animal`), characterclass.RangerClassID, 2},
	{SpellID(`Owl's Wisdom`), characterclass.RangerClassID, 2},
	{SpellID(`Protection from Energy`), characterclass.RangerClassID, 2},
	{SpellID(`Snare`), characterclass.RangerClassID, 2},
	{SpellID(`Speak with Plants`), characterclass.RangerClassID, 2},
	{SpellID(`Spike Growth`), characterclass.RangerClassID, 2},
	{SpellID(`Summon Nature's Ally 2`), characterclass.RangerClassID, 2},
	{SpellID(`Wind Wall`), characterclass.RangerClassID, 2},
	{SpellID(`Command Plants`), characterclass.RangerClassID, 3},
	{SpellID(`Cure Moderate Wounds`), characterclass.RangerClassID, 3},
	{SpellID(`Darkvision`), characterclass.RangerClassID, 3},
	{SpellID(`Diminish Plants`), characterclass.RangerClassID, 3},
	{SpellID(`Magic Fang, Greater`), characterclass.RangerClassID, 3},
	{SpellID(`Neutralize Poison`), characterclass.RangerClassID, 3},
	{SpellID(`Plant Growth`), characterclass.RangerClassID, 3},
	{SpellID(`Reduce Animal`), characterclass.RangerClassID, 3},
	{SpellID(`Remove Disease`), characterclass.RangerClassID, 3},
	{SpellID(`Repel Vermin`), characterclass.RangerClassID, 3},
	{SpellID(`Summon Nature's Ally 3`), characterclass.RangerClassID, 3},
	{SpellID(`Tree Shape`), characterclass.RangerClassID, 3},
	{SpellID(`Water Walk`), characterclass.RangerClassID, 3},
	{SpellID(`Animal Growth`), characterclass.RangerClassID, 4},
	{SpellID(`Commune with Nature`), characterclass.RangerClassID, 4},
	{SpellID(`Cure Serious Wounds`), characterclass.RangerClassID, 4},
	{SpellID(`Freedom of Movement`), characterclass.RangerClassID, 4},
	{SpellID(`Nondetection`), characterclass.RangerClassID, 4},
	{SpellID(`Summon Nature's Ally 4`), characterclass.RangerClassID, 4},
	{SpellID(`Tree Stride`), characterclass.RangerClassID, 4},
	{SpellID(`Acid Splash`), characterclass.SorcererClassID, 0},
	{SpellID(`Arcane Mark`), characterclass.SorcererClassID, 0},
	{SpellID(`Bleed`), characterclass.SorcererClassID, 0},
	{SpellID(`Dancing Lights`), characterclass.SorcererClassID, 0},
	{SpellID(`Daze`), characterclass.SorcererClassID, 0},
	{SpellID(`Detect Magic`), characterclass.SorcererClassID, 0},
	{SpellID(`Detect Poison`), characterclass.SorcererClassID, 0},
	{SpellID(`Disrupt Undead`), characterclass.SorcererClassID, 0},
	{SpellID(`Flare`), characterclass.SorcererClassID, 0},
	{SpellID(`Ghost Sound`), characterclass.SorcererClassID, 0},
	{SpellID(`Light`), characterclass.SorcererClassID, 0},
	{SpellID(`Mage Hand`), characterclass.SorcererClassID, 0},
	{SpellID(`Mending`), characterclass.SorcererClassID, 0},
	{SpellID(`Message`), characterclass.SorcererClassID, 0},
	{SpellID(`Open/Close`), characterclass.SorcererClassID, 0},
	{SpellID(`Prestidigitation`), characterclass.SorcererClassID, 0},
	{SpellID(`Ray of Frost`), characterclass.SorcererClassID, 0},
	{SpellID(`Read Magic`), characterclass.SorcererClassID, 0},
	{SpellID(`Resistance`), characterclass.SorcererClassID, 0},
	{SpellID(`Touch of Fatigue`), characterclass.SorcererClassID, 0},
	{SpellID(`Alarm`), characterclass.SorcererClassID, 1},
	{SpellID(`Animate Rope`), characterclass.SorcererClassID, 1},
	{SpellID(`Burning Hands`), characterclass.SorcererClassID, 1},
	{SpellID(`Cause Fear`), characterclass.SorcererClassID, 1},
	{SpellID(`Charm Person`), characterclass.SorcererClassID, 1},
	{SpellID(`Chill Touch`), characterclass.SorcererClassID, 1},
	{SpellID(`Color Spray`), characterclass.SorcererClassID, 1},
	{SpellID(`Comprehend Languages`), characterclass.SorcererClassID, 1},
	{SpellID(`Detect Secret Doors`), characterclass.SorcererClassID, 1},
	{SpellID(`Detect Undead`), characterclass.SorcererClassID, 1},
	{SpellID(`Disguise Self`), characterclass.SorcererClassID, 1},
	{SpellID(`Endure Elements`), characterclass.SorcererClassID, 1},
	{SpellID(`Enlarge Person`), characterclass.SorcererClassID, 1},
	{SpellID(`Erase`), characterclass.SorcererClassID, 1},
	{SpellID(`Expeditious Retreat`), characterclass.SorcererClassID, 1},
	{SpellID(`Feather Fall`), characterclass.SorcererClassID, 1},
	{SpellID(`Floating Disk`), characterclass.SorcererClassID, 1},
	{SpellID(`Grease`), characterclass.SorcererClassID, 1},
	{SpellID(`Hold Portal`), characterclass.SorcererClassID, 1},
	{SpellID(`Hypnotism`), characterclass.SorcererClassID, 1},
	{SpellID(`Identify`), characterclass.SorcererClassID, 1},
	{SpellID(`Jump`), characterclass.SorcererClassID, 1},
	{SpellID(`Mage Armor`), characterclass.SorcererClassID, 1},
	{SpellID(`Magic Aura`), characterclass.SorcererClassID, 1},
	{SpellID(`Magic Missile`), characterclass.SorcererClassID, 1},
	{SpellID(`Magic Weapon`), characterclass.SorcererClassID, 1},
	{SpellID(`Mount`), characterclass.SorcererClassID, 1},
	{SpellID(`Obscuring Mist`), characterclass.SorcererClassID, 1},
	{SpellID(`Protection from Chaos`), characterclass.SorcererClassID, 1},
	{SpellID(`Protection from Evil`), characterclass.SorcererClassID, 1},
	{SpellID(`Protection from Good`), characterclass.SorcererClassID, 1},
	{SpellID(`Protection from Law`), characterclass.SorcererClassID, 1},
	{SpellID(`Ray of Enfeeblement`), characterclass.SorcererClassID, 1},
	{SpellID(`Reduce Person`), characterclass.SorcererClassID, 1},
	{SpellID(`Shield`), characterclass.SorcererClassID, 1},
	{SpellID(`Shocking Grasp`), characterclass.SorcererClassID, 1},
	{SpellID(`Silent Image`), characterclass.SorcererClassID, 1},
	{SpellID(`Sleep`), characterclass.SorcererClassID, 1},
	{SpellID(`Summon Monster 1`), characterclass.SorcererClassID, 1},
	{SpellID(`True Strike`), characterclass.SorcererClassID, 1},
	{SpellID(`Unseen Servant`), characterclass.SorcererClassID, 1},
	{SpellID(`Ventriloquism`), characterclass.SorcererClassID, 1},
	{SpellID(`Acid Arrow`), characterclass.SorcererClassID, 2},
	{SpellID(`Alter Self`), characterclass.SorcererClassID, 2},
	{SpellID(`Arcane Lock`), characterclass.SorcererClassID, 2},
	{SpellID(`Bear's Endurance`), characterclass.SorcererClassID, 2},
	{SpellID(`Blindness/Deafness`), characterclass.SorcererClassID, 2},
	{SpellID(`Blur`), characterclass.SorcererClassID, 2},
	{SpellID(`Bull's Strength`), characterclass.SorcererClassID, 2},
	{SpellID(`Cat's Grace`), characterclass.SorcererClassID, 2},
	{SpellID(`Command Undead`), characterclass.SorcererClassID, 2},
	{SpellID(`Continual Flame`), characterclass.SorcererClassID, 2},
	{SpellID(`Darkness`), characterclass.SorcererClassID, 2},
	{SpellID(`Darkvision`), characterclass.SorcererClassID, 2},
	{SpellID(`Daze Monster`), characterclass.SorcererClassID, 2},
	{SpellID(`Detect Thoughts`), characterclass.SorcererClassID, 2},
	{SpellID(`Eagle's Splendor`), characterclass.SorcererClassID, 2},
	{SpellID(`False Life`), characterclass.SorcererClassID, 2},
	{SpellID(`Flaming Sphere`), characterclass.SorcererClassID, 2},
	{SpellID(`Fog Cloud`), characterclass.SorcererClassID, 2},
	{SpellID(`Fox's Cunning`), characterclass.SorcererClassID, 2},
	{SpellID(`Ghoul Touch`), characterclass.SorcererClassID, 2},
	{SpellID(`Glitterdust`), characterclass.SorcererClassID, 2},
	{SpellID(`Gust of Wind`), characterclass.SorcererClassID, 2},
	{SpellID(`Hideous Laughter`), characterclass.SorcererClassID, 2},
	{SpellID(`Hypnotic Pattern`), characterclass.SorcererClassID, 2},
	{SpellID(`Invisibility`), characterclass.SorcererClassID, 2},
	{SpellID(`Knock`), characterclass.SorcererClassID, 2},
	{SpellID(`Levitate`), characterclass.SorcererClassID, 2},
	{SpellID(`Locate Object`), characterclass.SorcererClassID, 2},
	{SpellID(`Magic Mouth`), characterclass.SorcererClassID, 2},
	{SpellID(`Make Whole`), characterclass.SorcererClassID, 2},
	{SpellID(`Minor Image`), characterclass.SorcererClassID, 2},
	{SpellID(`Mirror Image`), characterclass.SorcererClassID, 2},
	{SpellID(`Misdirection`), characterclass.SorcererClassID, 2},
	{SpellID(`Obscure Object`), characterclass.SorcererClassID, 2},
	{SpellID(`Owl's Wisdom`), characterclass.SorcererClassID, 2},
	{SpellID(`Phantom Trap`), characterclass.SorcererClassID, 2},
	{SpellID(`Protection from Arrows`), characterclass.SorcererClassID, 2},
	{SpellID(`Pyrotechnics`), characterclass.SorcererClassID, 2},
	{SpellID(`Resist Energy`), characterclass.SorcererClassID, 2},
	{SpellID(`Rope Trick`), characterclass.SorcererClassID, 2},
	{SpellID(`Scare`), characterclass.SorcererClassID, 2},
	{SpellID(`Scorching Ray`), characterclass.SorcererClassID, 2},
	{SpellID(`See Invisibility`), characterclass.SorcererClassID, 2},
	{SpellID(`Shatter`), characterclass.SorcererClassID, 2},
	{SpellID(`Spectral Hand`), characterclass.SorcererClassID, 2},
	{SpellID(`Spider Climb`), characterclass.SorcererClassID, 2},
	{SpellID(`Summon Monster 2`), characterclass.SorcererClassID, 2},
	{SpellID(`Summon Swarm`), characterclass.SorcererClassID, 2},
	{SpellID(`Touch of Idiocy`), characterclass.SorcererClassID, 2},
	{SpellID(`Web`), characterclass.SorcererClassID, 2},
	{SpellID(`Whispering Wind`), characterclass.SorcererClassID, 2},
	{SpellID(`Arcane Sight`), characterclass.SorcererClassID, 3},
	{SpellID(`Beast Shape I`), characterclass.SorcererClassID, 3},
	{SpellID(`Blink`), characterclass.SorcererClassID, 3},
	{SpellID(`Clairaudience/Clairvoyance`), characterclass.SorcererClassID, 3},
	{SpellID(`Daylight`), characterclass.SorcererClassID, 3},
	{SpellID(`Deep Slumber`), characterclass.SorcererClassID, 3},
	{SpellID(`Dispel Magic`), characterclass.SorcererClassID, 3},
	{SpellID(`Displacement`), characterclass.SorcererClassID, 3},
	{SpellID(`Explosive Runes`), characterclass.SorcererClassID, 3},
	{SpellID(`Fireball`), characterclass.SorcererClassID, 3},
	{SpellID(`Flame Arrow`), characterclass.SorcererClassID, 3},
	{SpellID(`Fly`), characterclass.SorcererClassID, 3},
	{SpellID(`Gaseous Form`), characterclass.SorcererClassID, 3},
	{SpellID(`Gentle Repose`), characterclass.SorcererClassID, 3},
	{SpellID(`Halt Undead`), characterclass.SorcererClassID, 3},
	{SpellID(`Haste`), characterclass.SorcererClassID, 3},
	{SpellID(`Heroism`), characterclass.SorcererClassID, 3},
	{SpellID(`Hold Person`), characterclass.SorcererClassID, 3},
	{SpellID(`Illusory Script`), characterclass.SorcererClassID, 3},
	{SpellID(`Invisibility Sphere`), characterclass.SorcererClassID, 3},
	{SpellID(`Keen Edge`), characterclass.SorcererClassID, 3},
	{SpellID(`Lightning Bolt`), characterclass.SorcererClassID, 3},
	{SpellID(`Magic Circle against Chaos`), characterclass.SorcererClassID, 3},
	{SpellID(`Magic Circle against Evil`), characterclass.SorcererClassID, 3},
	{SpellID(`Magic Circle against Good`), characterclass.SorcererClassID, 3},
	{SpellID(`Magic Circle against Law`), characterclass.SorcererClassID, 3},
	{SpellID(`Magic Weapon, Greater`), characterclass.SorcererClassID, 3},
	{SpellID(`Major Image`), characterclass.SorcererClassID, 3},
	{SpellID(`Nondetection`), characterclass.SorcererClassID, 3},
	{SpellID(`Phantom Steed`), characterclass.SorcererClassID, 3},
	{SpellID(`Protection from Energy`), characterclass.SorcererClassID, 3},
	{SpellID(`Rage`), characterclass.SorcererClassID, 3},
	{SpellID(`Ray of Exhaustion`), characterclass.SorcererClassID, 3},
	{SpellID(`Secret Page`), characterclass.SorcererClassID, 3},
	{SpellID(`Sepia Snake Sigil`), characterclass.SorcererClassID, 3},
	{SpellID(`Shrink Item`), characterclass.SorcererClassID, 3},
	{SpellID(`Sleet Storm`), characterclass.SorcererClassID, 3},
	{SpellID(`Slow`), characterclass.SorcererClassID, 3},
	{SpellID(`Stinking Cloud`), characterclass.SorcererClassID, 3},
	{SpellID(`Suggestion`), characterclass.SorcererClassID, 3},
	{SpellID(`Summon Monster 3`), characterclass.SorcererClassID, 3},
	{SpellID(`Tiny Hut`), characterclass.SorcererClassID, 3},
	{SpellID(`Tongues`), characterclass.SorcererClassID, 3},
	{SpellID(`Vampiric Touch`), characterclass.SorcererClassID, 3},
	{SpellID(`Water Breathing`), characterclass.SorcererClassID, 3},
	{SpellID(`Wind Wall`), characterclass.SorcererClassID, 3},
	{SpellID(`Animate Dead`), characterclass.SorcererClassID, 4},
	{SpellID(`Arcane Eye`), characterclass.SorcererClassID, 4},
	{SpellID(`Beast Shape II`), characterclass.SorcererClassID, 4},
	{SpellID(`Bestow Curse`), characterclass.SorcererClassID, 4},
	{SpellID(`Black Tentacles`), characterclass.SorcererClassID, 4},
	{SpellID(`Charm Monster`), characterclass.SorcererClassID, 4},
	{SpellID(`Confusion`), characterclass.SorcererClassID, 4},
	{SpellID(`Contagion`), characterclass.SorcererClassID, 4},
	{SpellID(`Crushing Despair`), characterclass.SorcererClassID, 4},
	{SpellID(`Detect Scrying`), characterclass.SorcererClassID, 4},
	{SpellID(`Dimension Door`), characterclass.SorcererClassID, 4},
	{SpellID(`Dimensional Anchor`), characterclass.SorcererClassID, 4},
	{SpellID(`Elemental Body I`), characterclass.SorcererClassID, 4},
	{SpellID(`Enervation`), characterclass.SorcererClassID, 4},
	{SpellID(`Enlarge Person, Mass`), characterclass.SorcererClassID, 4},
	{SpellID(`Fear`), characterclass.SorcererClassID, 4},
	{SpellID(`Fire Shield`), characterclass.SorcererClassID, 4},
	{SpellID(`Fire Trap`), characterclass.SorcererClassID, 4},
	{SpellID(`Geas, Lesser`), characterclass.SorcererClassID, 4},
	{SpellID(`Globe of Invulnerability, Lesser`), characterclass.SorcererClassID, 4},
	{SpellID(`Hallucinatory Terrain`), characterclass.SorcererClassID, 4},
	{SpellID(`Ice Storm`), characterclass.SorcererClassID, 4},
	{SpellID(`Illusory Wall`), characterclass.SorcererClassID, 4},
	{SpellID(`Invisibility, Greater`), characterclass.SorcererClassID, 4},
	{SpellID(`Locate Creature`), characterclass.SorcererClassID, 4},
	{SpellID(`Minor Creation`), characterclass.SorcererClassID, 4},
	{SpellID(`Phantasmal Killer`), characterclass.SorcererClassID, 4},
	{SpellID(`Rainbow Pattern`), characterclass.SorcererClassID, 4},
	{SpellID(`Reduce Person, Mass`), characterclass.SorcererClassID, 4},
	{SpellID(`Remove Curse`), characterclass.SorcererClassID, 4},
	{SpellID(`Resilient Sphere`), characterclass.SorcererClassID, 4},
	{SpellID(`Scrying`), characterclass.SorcererClassID, 4},
	{SpellID(`Secure Shelter`), characterclass.SorcererClassID, 4},
	{SpellID(`Shadow Conjuration`), characterclass.SorcererClassID, 4},
	{SpellID(`Shout`), characterclass.SorcererClassID, 4},
	{SpellID(`Solid Fog`), characterclass.SorcererClassID, 4},
	{SpellID(`Stone Shape`), characterclass.SorcererClassID, 4},
	{SpellID(`Stoneskin`), characterclass.SorcererClassID, 4},
	{SpellID(`Summon Monster 4`), characterclass.SorcererClassID, 4},
	{SpellID(`Wall of Fire`), characterclass.SorcererClassID, 4},
	{SpellID(`Wall of Ice`), characterclass.SorcererClassID, 4},
	{SpellID(`Animal Growth`), characterclass.SorcererClassID, 5},
	{SpellID(`Baleful Polymorph`), characterclass.SorcererClassID, 5},
	{SpellID(`Beast Shape III`), characterclass.SorcererClassID, 5},
	{SpellID(`Blight`), characterclass.SorcererClassID, 5},
	{SpellID(`Break Enchantment`), characterclass.SorcererClassID, 5},
	{SpellID(`Cloudkill`), characterclass.SorcererClassID, 5},
	{SpellID(`Cone of Cold`), characterclass.SorcererClassID, 5},
	{SpellID(`Contact Other Plane`), characterclass.SorcererClassID, 5},
	{SpellID(`Dismissal`), characterclass.SorcererClassID, 5},
	{SpellID(`Dominate Person`), characterclass.SorcererClassID, 5},
	{SpellID(`Dream`), characterclass.SorcererClassID, 5},
	{SpellID(`Elemental Body II`), characterclass.SorcererClassID, 5},
	{SpellID(`Fabricate`), characterclass.SorcererClassID, 5},
	{SpellID(`False Vision`), characterclass.SorcererClassID, 5},
	{SpellID(`Feeblemind`), characterclass.SorcererClassID, 5},
	{SpellID(`Hold Monster`), characterclass.SorcererClassID, 5},
	{SpellID(`Interposing Hand`), characterclass.SorcererClassID, 5},
	{SpellID(`Mage's Faithful Hound`), characterclass.SorcererClassID, 5},
	{SpellID(`Mage's Private Sanctum`), characterclass.SorcererClassID, 5},
	{SpellID(`Magic Jar`), characterclass.SorcererClassID, 5},
	{SpellID(`Major Creation`), characterclass.SorcererClassID, 5},
	{SpellID(`Mind Fog`), characterclass.SorcererClassID, 5},
	{SpellID(`Mirage Arcana`), characterclass.SorcererClassID, 5},
	{SpellID(`Nightmare`), characterclass.SorcererClassID, 5},
	{SpellID(`Overland Flight`), characterclass.SorcererClassID, 5},
	{SpellID(`Passwall`), characterclass.SorcererClassID, 5},
	{SpellID(`Permanency`), characterclass.SorcererClassID, 5},
	{SpellID(`Persistent Image`), characterclass.SorcererClassID, 5},
	{SpellID(`Planar Binding, Lesser`), characterclass.SorcererClassID, 5},
	{SpellID(`Plant Shape I`), characterclass.SorcererClassID, 5},
	{SpellID(`Polymorph`), characterclass.SorcererClassID, 5},
	{SpellID(`Prying Eyes`), characterclass.SorcererClassID, 5},
	{SpellID(`Secret Chest`), characterclass.SorcererClassID, 5},
	{SpellID(`Seeming`), characterclass.SorcererClassID, 5},
	{SpellID(`Sending`), characterclass.SorcererClassID, 5},
	{SpellID(`Shadow Evocation`), characterclass.SorcererClassID, 5},
	{SpellID(`Summon Monster 5`), characterclass.SorcererClassID, 5},
	{SpellID(`Symbol of Pain`), characterclass.SorcererClassID, 5},
	{SpellID(`Symbol of Sleep`), characterclass.SorcererClassID, 5},
	{SpellID(`Telekinesis`), characterclass.SorcererClassID, 5},
	{SpellID(`Telepathic Bond`), characterclass.SorcererClassID, 5},
	{SpellID(`Teleport`), characterclass.SorcererClassID, 5},
	{SpellID(`Transmute Mud to Rock`), characterclass.SorcererClassID, 5},
	{SpellID(`Transmute Rock to Mud`), characterclass.SorcererClassID, 5},
	{SpellID(`Wall of Force`), characterclass.SorcererClassID, 5},
	{SpellID(`Wall of Stone`), characterclass.SorcererClassID, 5},
	{SpellID(`Waves of Fatigue`), characterclass.SorcererClassID, 5},
	{SpellID(`Acid Fog`), characterclass.SorcererClassID, 6},
	{SpellID(`Analyze Dweomer`), characterclass.SorcererClassID, 6},
	{SpellID(`Antimagic Field`), characterclass.SorcererClassID, 6},
	{SpellID(`Bear's Endurance, Mass`), characterclass.SorcererClassID, 6},
	{SpellID(`Beast Shape IV`), characterclass.SorcererClassID, 6},
	{SpellID(`Bull's Strength, Mass`), characterclass.SorcererClassID, 6},
	{SpellID(`Cat's Grace, Mass`), characterclass.SorcererClassID, 6},
	{SpellID(`Chain Lightning`), characterclass.SorcererClassID, 6},
	{SpellID(`Circle of Death`), characterclass.SorcererClassID, 6},
	{SpellID(`Contingency`), characterclass.SorcererClassID, 6},
	{SpellID(`Control Water`), characterclass.SorcererClassID, 6},
	{SpellID(`Create Undead`), characterclass.SorcererClassID, 6},
	{SpellID(`Disintegrate`), characterclass.SorcererClassID, 6},
	{SpellID(`Dispel Magic, Greater`), characterclass.SorcererClassID, 6},
	{SpellID(`Eagle's Splendor, Mass`), characterclass.SorcererClassID, 6},
	{SpellID(`Elemental Body III`), characterclass.SorcererClassID, 6},
	{SpellID(`Eyebite`), characterclass.SorcererClassID, 6},
	{SpellID(`Flesh to Stone`), characterclass.SorcererClassID, 6},
	{SpellID(`Forceful Hand`), characterclass.SorcererClassID, 6},
	{SpellID(`Form of the Dragon I`), characterclass.SorcererClassID, 6},
	{SpellID(`Fox's Cunning, Mass`), characterclass.SorcererClassID, 6},
	{SpellID(`Freezing Sphere`), characterclass.SorcererClassID, 6},
	{SpellID(`Geas/Quest`), characterclass.SorcererClassID, 6},
	{SpellID(`Globe of Invulnerability`), characterclass.SorcererClassID, 6},
	{SpellID(`Guards and Wards`), characterclass.SorcererClassID, 6},
	{SpellID(`Heroism, Greater`), characterclass.SorcererClassID, 6},
	{SpellID(`Legend Lore`), characterclass.SorcererClassID, 6},
	{SpellID(`Mislead`), characterclass.SorcererClassID, 6},
	{SpellID(`Move Earth`), characterclass.SorcererClassID, 6},
	{SpellID(`Owl's Wisdom, Mass`), characterclass.SorcererClassID, 6},
	{SpellID(`Permanent Image`), characterclass.SorcererClassID, 6},
	{SpellID(`Planar Binding`), characterclass.SorcererClassID, 6},
	{SpellID(`Plant Shape II`), characterclass.SorcererClassID, 6},
	{SpellID(`Programmed Image`), characterclass.SorcererClassID, 6},
	{SpellID(`Repulsion`), characterclass.SorcererClassID, 6},
	{SpellID(`Shadow Walk`), characterclass.SorcererClassID, 6},
	{SpellID(`Stone to Flesh`), characterclass.SorcererClassID, 6},
	{SpellID(`Suggestion, Mass`), characterclass.SorcererClassID, 6},
	{SpellID(`Summon Monster 6`), characterclass.SorcererClassID, 6},
	{SpellID(`Symbol of Fear`), characterclass.SorcererClassID, 6},
	{SpellID(`Symbol of Persuasion`), characterclass.SorcererClassID, 6},
	{SpellID(`Transformation`), characterclass.SorcererClassID, 6},
	{SpellID(`True Seeing`), characterclass.SorcererClassID, 6},
	{SpellID(`Undeath to Death`), characterclass.SorcererClassID, 6},
	{SpellID(`Veil`), characterclass.SorcererClassID, 6},
	{SpellID(`Wall of Iron`), characterclass.SorcererClassID, 6},
	{SpellID(`Arcane Sight, Greater`), characterclass.SorcererClassID, 7},
	{SpellID(`Banishment`), characterclass.SorcererClassID, 7},
	{SpellID(`Control Undead`), characterclass.SorcererClassID, 7},
	{SpellID(`Control Weather`), characterclass.SorcererClassID, 7},
	{SpellID(`Delayed Blast Fireball`), characterclass.SorcererClassID, 7},
	{SpellID(`Elemental Body IV`), characterclass.SorcererClassID, 7},
	{SpellID(`Ethereal Jaunt`), characterclass.SorcererClassID, 7},
	{SpellID(`Finger of Death`), characterclass.SorcererClassID, 7},
	{SpellID(`Forcecage`), characterclass.SorcererClassID, 7},
	{SpellID(`Form of the Dragon II`), characterclass.SorcererClassID, 7},
	{SpellID(`Giant Form I`), characterclass.SorcererClassID, 7},
	{SpellID(`Grasping Hand`), characterclass.SorcererClassID, 7},
	{SpellID(`Hold Person, Mass`), characterclass.SorcererClassID, 7},
	{SpellID(`Insanity`), characterclass.SorcererClassID, 7},
	{SpellID(`Instant Summons`), characterclass.SorcererClassID, 7},
	{SpellID(`Invisibility, Mass`), characterclass.SorcererClassID, 7},
	{SpellID(`Limited Wish`), characterclass.SorcererClassID, 7},
	{SpellID(`Mage's Magnificent Mansion`), characterclass.SorcererClassID, 7},
	{SpellID(`Mage's Sword`), characterclass.SorcererClassID, 7},
	{SpellID(`Phase Door`), characterclass.SorcererClassID, 7},
	{SpellID(`Plane Shift`), characterclass.SorcererClassID, 7},
	{SpellID(`Plant Shape III`), characterclass.SorcererClassID, 7},
	{SpellID(`Polymorph, Greater`), characterclass.SorcererClassID, 7},
	{SpellID(`Power Word Blind`), characterclass.SorcererClassID, 7},
	{SpellID(`Prismatic Spray`), characterclass.SorcererClassID, 7},
	{SpellID(`Project Image`), characterclass.SorcererClassID, 7},
	{SpellID(`Reverse Gravity`), characterclass.SorcererClassID, 7},
	{SpellID(`Scrying, Greater`), characterclass.SorcererClassID, 7},
	{SpellID(`Sequester`), characterclass.SorcererClassID, 7},
	{SpellID(`Shadow Conjuration, Greater`), characterclass.SorcererClassID, 7},
	{SpellID(`Simulacrum`), characterclass.SorcererClassID, 7},
	{SpellID(`Spell Turning`), characterclass.SorcererClassID, 7},
	{SpellID(`Statue`), characterclass.SorcererClassID, 7},
	{SpellID(`Summon Monster 7`), characterclass.SorcererClassID, 7},
	{SpellID(`Symbol of Stunning`), characterclass.SorcererClassID, 7},
	{SpellID(`Symbol of Weakness`), characterclass.SorcererClassID, 7},
	{SpellID(`Teleport Object`), characterclass.SorcererClassID, 7},
	{SpellID(`Teleport, Greater`), characterclass.SorcererClassID, 7},
	{SpellID(`Vision`), characterclass.SorcererClassID, 7},
	{SpellID(`Waves of Exhaustion`), characterclass.SorcererClassID, 7},
	{SpellID(`Antipathy`), characterclass.SorcererClassID, 8},
	{SpellID(`Binding`), characterclass.SorcererClassID, 8},
	{SpellID(`Charm Monster, Mass`), characterclass.SorcererClassID, 8},
	{SpellID(`Clenched Fist`), characterclass.SorcererClassID, 8},
	{SpellID(`Clone`), characterclass.SorcererClassID, 8},
	{SpellID(`Create Greater Undead`), characterclass.SorcererClassID, 8},
	{SpellID(`Demand`), characterclass.SorcererClassID, 8},
	{SpellID(`Dimensional Lock`), characterclass.SorcererClassID, 8},
	{SpellID(`Discern Location`), characterclass.SorcererClassID, 8},
	{SpellID(`Form of the Dragon III`), characterclass.SorcererClassID, 8},
	{SpellID(`Giant Form II`), characterclass.SorcererClassID, 8},
	{SpellID(`Horrid Wilting`), characterclass.SorcererClassID, 8},
	{SpellID(`Incendiary Cloud`), characterclass.SorcererClassID, 8},
	{SpellID(`Iron Body`), characterclass.SorcererClassID, 8},
	{SpellID(`Irresistible Dance`), characterclass.SorcererClassID, 8},
	{SpellID(`Maze`), characterclass.SorcererClassID, 8},
	{SpellID(`Mind Blank`), characterclass.SorcererClassID, 8},
	{SpellID(`Moment of Prescience`), characterclass.SorcererClassID, 8},
	{SpellID(`Planar Binding, Greater`), characterclass.SorcererClassID, 8},
	{SpellID(`Polar Ray`), characterclass.SorcererClassID, 8},
	{SpellID(`Polymorph Any Object`), characterclass.SorcererClassID, 8},
	{SpellID(`Power Word Stun`), characterclass.SorcererClassID, 8},
	{SpellID(`Prismatic Wall`), characterclass.SorcererClassID, 8},
	{SpellID(`Protection from Spells`), characterclass.SorcererClassID, 8},
	{SpellID(`Prying Eyes, Greater`), characterclass.SorcererClassID, 8},
	{SpellID(`Scintillating Pattern`), characterclass.SorcererClassID, 8},
	{SpellID(`Screen`), characterclass.SorcererClassID, 8},
	{SpellID(`Shadow Evocation, Greater`), characterclass.SorcererClassID, 8},
	{SpellID(`Shout, Greater`), characterclass.SorcererClassID, 8},
	{SpellID(`Summon Monster 8`), characterclass.SorcererClassID, 8},
	{SpellID(`Sunburst`), characterclass.SorcererClassID, 8},
	{SpellID(`Symbol of Death`), characterclass.SorcererClassID, 8},
	{SpellID(`Symbol of Insanity`), characterclass.SorcererClassID, 8},
	{SpellID(`Sympathy`), characterclass.SorcererClassID, 8},
	{SpellID(`Telekinetic Sphere`), characterclass.SorcererClassID, 8},
	{SpellID(`Temporal Stasis`), characterclass.SorcererClassID, 8},
	{SpellID(`Trap the Soul`), characterclass.SorcererClassID, 8},
	{SpellID(`Astral Projection`), characterclass.SorcererClassID, 9},
	{SpellID(`Crushing Hand`), characterclass.SorcererClassID, 9},
	{SpellID(`Dominate Monster`), characterclass.SorcererClassID, 9},
	{SpellID(`Energy Drain`), characterclass.SorcererClassID, 9},
	{SpellID(`Etherealness`), characterclass.SorcererClassID, 9},
	{SpellID(`Foresight`), characterclass.SorcererClassID, 9},
	{SpellID(`Freedom`), characterclass.SorcererClassID, 9},
	{SpellID(`Gate`), characterclass.SorcererClassID, 9},
	{SpellID(`Hold Monster, Mass`), characterclass.SorcererClassID, 9},
	{SpellID(`Imprisonment`), characterclass.SorcererClassID, 9},
	{SpellID(`Mage's Disjunction`), characterclass.SorcererClassID, 9},
	{SpellID(`Meteor Swarm`), characterclass.SorcererClassID, 9},
	{SpellID(`Power Word Kill`), characterclass.SorcererClassID, 9},
	{SpellID(`Prismatic Sphere`), characterclass.SorcererClassID, 9},
	{SpellID(`Refuge`), characterclass.SorcererClassID, 9},
	{SpellID(`Shades`), characterclass.SorcererClassID, 9},
	{SpellID(`Shapechange`), characterclass.SorcererClassID, 9},
	{SpellID(`Soul Bind`), characterclass.SorcererClassID, 9},
	{SpellID(`Summon Monster 9`), characterclass.SorcererClassID, 9},
	{SpellID(`Teleportation Circle`), characterclass.SorcererClassID, 9},
	{SpellID(`Time Stop`), characterclass.SorcererClassID, 9},
	{SpellID(`Wail of the Banshee`), characterclass.SorcererClassID, 9},
	{SpellID(`Weird`), characterclass.SorcererClassID, 9},
	{SpellID(`Wish`), characterclass.SorcererClassID, 9},
	{SpellID(`Acid Splash`), characterclass.WizardClassID, 0},
	{SpellID(`Arcane Mark`), characterclass.WizardClassID, 0},
	{SpellID(`Bleed`), characterclass.WizardClassID, 0},
	{SpellID(`Dancing Lights`), characterclass.WizardClassID, 0},
	{SpellID(`Daze`), characterclass.WizardClassID, 0},
	{SpellID(`Detect Magic`), characterclass.WizardClassID, 0},
	{SpellID(`Detect Poison`), characterclass.WizardClassID, 0},
	{SpellID(`Disrupt Undead`), characterclass.WizardClassID, 0},
	{SpellID(`Flare`), characterclass.WizardClassID, 0},
	{SpellID(`Ghost Sound`), characterclass.WizardClassID, 0},
	{SpellID(`Light`), characterclass.WizardClassID, 0},
	{SpellID(`Mage Hand`), characterclass.WizardClassID, 0},
	{SpellID(`Mending`), characterclass.WizardClassID, 0},
	{SpellID(`Message`), characterclass.WizardClassID, 0},
	{SpellID(`Open/Close`), characterclass.WizardClassID, 0},
	{SpellID(`Prestidigitation`), characterclass.WizardClassID, 0},
	{SpellID(`Ray of Frost`), characterclass.WizardClassID, 0},
	{SpellID(`Read Magic`), characterclass.WizardClassID, 0},
	{SpellID(`Resistance`), characterclass.WizardClassID, 0},
	{SpellID(`Touch of Fatigue`), characterclass.WizardClassID, 0},
	{SpellID(`Alarm`), characterclass.WizardClassID, 1},
	{SpellID(`Animate Rope`), characterclass.WizardClassID, 1},
	{SpellID(`Burning Hands`), characterclass.WizardClassID, 1},
	{SpellID(`Cause Fear`), characterclass.WizardClassID, 1},
	{SpellID(`Charm Person`), characterclass.WizardClassID, 1},
	{SpellID(`Chill Touch`), characterclass.WizardClassID, 1},
	{SpellID(`Color Spray`), characterclass.WizardClassID, 1},
	{SpellID(`Comprehend Languages`), characterclass.WizardClassID, 1},
	{SpellID(`Detect Secret Doors`), characterclass.WizardClassID, 1},
	{SpellID(`Detect Undead`), characterclass.WizardClassID, 1},
	{SpellID(`Disguise Self`), characterclass.WizardClassID, 1},
	{SpellID(`Endure Elements`), characterclass.WizardClassID, 1},
	{SpellID(`Enlarge Person`), characterclass.WizardClassID, 1},
	{SpellID(`Erase`), characterclass.WizardClassID, 1},
	{SpellID(`Expeditious Retreat`), characterclass.WizardClassID, 1},
	{SpellID(`Feather Fall`), characterclass.WizardClassID, 1},
	{SpellID(`Floating Disk`), characterclass.WizardClassID, 1},
	{SpellID(`Grease`), characterclass.WizardClassID, 1},
	{SpellID(`Hold Portal`), characterclass.WizardClassID, 1},
	{SpellID(`Hypnotism`), characterclass.WizardClassID, 1},
	{SpellID(`Identify`), characterclass.WizardClassID, 1},
	{SpellID(`Jump`), characterclass.WizardClassID, 1},
	{SpellID(`Mage Armor`), characterclass.WizardClassID, 1},
	{SpellID(`Magic Aura`), characterclass.WizardClassID, 1},
	{SpellID(`Magic Missile`), characterclass.WizardClassID, 1},
	{SpellID(`Magic Weapon`), characterclass.WizardClassID, 1},
	{SpellID(`Mount`), characterclass.WizardClassID, 1},
	{SpellID(`Obscuring Mist`), characterclass.WizardClassID, 1},
	{SpellID(`Protection from Chaos`), characterclass.WizardClassID, 1},
	{SpellID(`Protection from Evil`), characterclass.WizardClassID, 1},
	{SpellID(`Protection from Good`), characterclass.WizardClassID, 1},
	{SpellID(`Protection from Law`), characterclass.WizardClassID, 1},
	{SpellID(`Ray of Enfeeblement`), characterclass.WizardClassID, 1},
	{SpellID(`Reduce Person`), characterclass.WizardClassID, 1},
	{SpellID(`Shield`), characterclass.WizardClassID, 1},
	{SpellID(`Shocking Grasp`), characterclass.WizardClassID, 1},
	{SpellID(`Silent Image`), characterclass.WizardClassID, 1},
	{SpellID(`Sleep`), characterclass.WizardClassID, 1},
	{SpellID(`Summon Monster 1`), characterclass.WizardClassID, 1},
	{SpellID(`True Strike`), characterclass.WizardClassID, 1},
	{SpellID(`Unseen Servant`), characterclass.WizardClassID, 1},
	{SpellID(`Ventriloquism`), characterclass.WizardClassID, 1},
	{SpellID(`Acid Arrow`), characterclass.WizardClassID, 2},
	{SpellID(`Alter Self`), characterclass.WizardClassID, 2},
	{SpellID(`Arcane Lock`), characterclass.WizardClassID, 2},
	{SpellID(`Bear's Endurance`), characterclass.WizardClassID, 2},
	{SpellID(`Blindness/Deafness`), characterclass.WizardClassID, 2},
	{SpellID(`Blur`), characterclass.WizardClassID, 2},
	{SpellID(`Bull's Strength`), characterclass.WizardClassID, 2},
	{SpellID(`Cat's Grace`), characterclass.WizardClassID, 2},
	{SpellID(`Command Undead`), characterclass.WizardClassID, 2},
	{SpellID(`Continual Flame`), characterclass.WizardClassID, 2},
	{SpellID(`Darkness`), characterclass.WizardClassID, 2},
	{SpellID(`Darkvision`), characterclass.WizardClassID, 2},
	{SpellID(`Daze Monster`), characterclass.WizardClassID, 2},
	{SpellID(`Detect Thoughts`), characterclass.WizardClassID, 2},
	{SpellID(`Eagle's Splendor`), characterclass.WizardClassID, 2},
	{SpellID(`False Life`), characterclass.WizardClassID, 2},
	{SpellID(`Flaming Sphere`), characterclass.WizardClassID, 2},
	{SpellID(`Fog Cloud`), characterclass.WizardClassID, 2},
	{SpellID(`Fox's Cunning`), characterclass.WizardClassID, 2},
	{SpellID(`Ghoul Touch`), characterclass.WizardClassID, 2},
	{SpellID(`Glitterdust`), characterclass.WizardClassID, 2},
	{SpellID(`Gust of Wind`), characterclass.WizardClassID, 2},
	{SpellID(`Hideous Laughter`), characterclass.WizardClassID, 2},
	{SpellID(`Hypnotic Pattern`), characterclass.WizardClassID, 2},
	{SpellID(`Invisibility`), characterclass.WizardClassID, 2},
	{SpellID(`Knock`), characterclass.WizardClassID, 2},
	{SpellID(`Levitate`), characterclass.WizardClassID, 2},
	{SpellID(`Locate Object`), characterclass.WizardClassID, 2},
	{SpellID(`Magic Mouth`), characterclass.WizardClassID, 2},
	{SpellID(`Make Whole`), characterclass.WizardClassID, 2},
	{SpellID(`Minor Image`), characterclass.WizardClassID, 2},
	{SpellID(`Mirror Image`), characterclass.WizardClassID, 2},
	{SpellID(`Misdirection`), characterclass.WizardClassID, 2},
	{SpellID(`Obscure Object`), characterclass.WizardClassID, 2},
	{SpellID(`Owl's Wisdom`), characterclass.WizardClassID, 2},
	{SpellID(`Phantom Trap`), characterclass.WizardClassID, 2},
	{SpellID(`Protection from Arrows`), characterclass.WizardClassID, 2},
	{SpellID(`Pyrotechnics`), characterclass.WizardClassID, 2},
	{SpellID(`Resist Energy`), characterclass.WizardClassID, 2},
	{SpellID(`Rope Trick`), characterclass.WizardClassID, 2},
	{SpellID(`Scare`), characterclass.WizardClassID, 2},
	{SpellID(`Scorching Ray`), characterclass.WizardClassID, 2},
	{SpellID(`See Invisibility`), characterclass.WizardClassID, 2},
	{SpellID(`Shatter`), characterclass.WizardClassID, 2},
	{SpellID(`Spectral Hand`), characterclass.WizardClassID, 2},
	{SpellID(`Spider Climb`), characterclass.WizardClassID, 2},
	{SpellID(`Summon Monster 2`), characterclass.WizardClassID, 2},
	{SpellID(`Summon Swarm`), characterclass.WizardClassID, 2},
	{SpellID(`Touch of Idiocy`), characterclass.WizardClassID, 2},
	{SpellID(`Web`), characterclass.WizardClassID, 2},
	{SpellID(`Whispering Wind`), characterclass.WizardClassID, 2},
	{SpellID(`Arcane Sight`), characterclass.WizardClassID, 3},
	{SpellID(`Beast Shape I`), characterclass.WizardClassID, 3},
	{SpellID(`Blink`), characterclass.WizardClassID, 3},
	{SpellID(`Clairaudience/Clairvoyance`), characterclass.WizardClassID, 3},
	{SpellID(`Daylight`), characterclass.WizardClassID, 3},
	{SpellID(`Deep Slumber`), characterclass.WizardClassID, 3},
	{SpellID(`Dispel Magic`), characterclass.WizardClassID, 3},
	{SpellID(`Displacement`), characterclass.WizardClassID, 3},
	{SpellID(`Explosive Runes`), characterclass.WizardClassID, 3},
	{SpellID(`Fireball`), characterclass.WizardClassID, 3},
	{SpellID(`Flame Arrow`), characterclass.WizardClassID, 3},
	{SpellID(`Fly`), characterclass.WizardClassID, 3},
	{SpellID(`Gaseous Form`), characterclass.WizardClassID, 3},
	{SpellID(`Gentle Repose`), characterclass.WizardClassID, 3},
	{SpellID(`Halt Undead`), characterclass.WizardClassID, 3},
	{SpellID(`Haste`), characterclass.WizardClassID, 3},
	{SpellID(`Heroism`), characterclass.WizardClassID, 3},
	{SpellID(`Hold Person`), characterclass.WizardClassID, 3},
	{SpellID(`Illusory Script`), characterclass.WizardClassID, 3},
	{SpellID(`Invisibility Sphere`), characterclass.WizardClassID, 3},
	{SpellID(`Keen Edge`), characterclass.WizardClassID, 3},
	{SpellID(`Lightning Bolt`), characterclass.WizardClassID, 3},
	{SpellID(`Magic Circle against Chaos`), characterclass.WizardClassID, 3},
	{SpellID(`Magic Circle against Evil`), characterclass.WizardClassID, 3},
	{SpellID(`Magic Circle against Good`), characterclass.WizardClassID, 3},
	{SpellID(`Magic Circle against Law`), characterclass.WizardClassID, 3},
	{SpellID(`Magic Weapon, Greater`), characterclass.WizardClassID, 3},
	{SpellID(`Major Image`), characterclass.WizardClassID, 3},
	{SpellID(`Nondetection`), characterclass.WizardClassID, 3},
	{SpellID(`Phantom Steed`), characterclass.WizardClassID, 3},
	{SpellID(`Protection from Energy`), characterclass.WizardClassID, 3},
	{SpellID(`Rage`), characterclass.WizardClassID, 3},
	{SpellID(`Ray of Exhaustion`), characterclass.WizardClassID, 3},
	{SpellID(`Secret Page`), characterclass.WizardClassID, 3},
	{SpellID(`Sepia Snake Sigil`), characterclass.WizardClassID, 3},
	{SpellID(`Shrink Item`), characterclass.WizardClassID, 3},
	{SpellID(`Sleet Storm`), characterclass.WizardClassID, 3},
	{SpellID(`Slow`), characterclass.WizardClassID, 3},
	{SpellID(`Stinking Cloud`), characterclass.WizardClassID, 3},
	{SpellID(`Suggestion`), characterclass.WizardClassID, 3},
	{SpellID(`Summon Monster 3`), characterclass.WizardClassID, 3},
	{SpellID(`Tiny Hut`), characterclass.WizardClassID, 3},
	{SpellID(`Tongues`), characterclass.WizardClassID, 3},
	{SpellID(`Vampiric Touch`), characterclass.WizardClassID, 3},
	{SpellID(`Water Breathing`), characterclass.WizardClassID, 3},
	{SpellID(`Wind Wall`), characterclass.WizardClassID, 3},
	{SpellID(`Animate Dead`), characterclass.WizardClassID, 4},
	{SpellID(`Arcane Eye`), characterclass.WizardClassID, 4},
	{SpellID(`Beast Shape II`), characterclass.WizardClassID, 4},
	{SpellID(`Bestow Curse`), characterclass.WizardClassID, 4},
	{SpellID(`Black Tentacles`), characterclass.WizardClassID, 4},
	{SpellID(`Charm Monster`), characterclass.WizardClassID, 4},
	{SpellID(`Confusion`), characterclass.WizardClassID, 4},
	{SpellID(`Contagion`), characterclass.WizardClassID, 4},
	{SpellID(`Crushing Despair`), characterclass.WizardClassID, 4},
	{SpellID(`Detect Scrying`), characterclass.WizardClassID, 4},
	{SpellID(`Dimension Door`), characterclass.WizardClassID, 4},
	{SpellID(`Dimensional Anchor`), characterclass.WizardClassID, 4},
	{SpellID(`Elemental Body I`), characterclass.WizardClassID, 4},
	{SpellID(`Enervation`), characterclass.WizardClassID, 4},
	{SpellID(`Enlarge Person, Mass`), characterclass.WizardClassID, 4},
	{SpellID(`Fear`), characterclass.WizardClassID, 4},
	{SpellID(`Fire Shield`), characterclass.WizardClassID, 4},
	{SpellID(`Fire Trap`), characterclass.WizardClassID, 4},
	{SpellID(`Geas, Lesser`), characterclass.WizardClassID, 4},
	{SpellID(`Globe of Invulnerability, Lesser`), characterclass.WizardClassID, 4},
	{SpellID(`Hallucinatory Terrain`), characterclass.WizardClassID, 4},
	{SpellID(`Ice Storm`), characterclass.WizardClassID, 4},
	{SpellID(`Illusory Wall`), characterclass.WizardClassID, 4},
	{SpellID(`Invisibility, Greater`), characterclass.WizardClassID, 4},
	{SpellID(`Locate Creature`), characterclass.WizardClassID, 4},
	{SpellID(`Minor Creation`), characterclass.WizardClassID, 4},
	{SpellID(`Mnemonic Enhancer`), characterclass.WizardClassID, 4},
	{SpellID(`Phantasmal Killer`), characterclass.WizardClassID, 4},
	{SpellID(`Rainbow Pattern`), characterclass.WizardClassID, 4},
	{SpellID(`Reduce Person, Mass`), characterclass.WizardClassID, 4},
	{SpellID(`Remove Curse`), characterclass.WizardClassID, 4},
	{SpellID(`Resilient Sphere`), characterclass.WizardClassID, 4},
	{SpellID(`Scrying`), characterclass.WizardClassID, 4},
	{SpellID(`Secure Shelter`), characterclass.WizardClassID, 4},
	{SpellID(`Shadow Conjuration`), characterclass.WizardClassID, 4},
	{SpellID(`Shout`), characterclass.WizardClassID, 4},
	{SpellID(`Solid Fog`), characterclass.WizardClassID, 4},
	{SpellID(`Stone Shape`), characterclass.WizardClassID, 4},
	{SpellID(`Stoneskin`), characterclass.WizardClassID, 4},
	{SpellID(`Summon Monster 4`), characterclass.WizardClassID, 4},
	{SpellID(`Wall of Fire`), characterclass.WizardClassID, 4},
	{SpellID(`Wall of Ice`), characterclass.WizardClassID, 4},
	{SpellID(`Animal Growth`), characterclass.WizardClassID, 5},
	{SpellID(`Baleful Polymorph`), characterclass.WizardClassID, 5},
	{SpellID(`Beast Shape III`), characterclass.WizardClassID, 5},
	{SpellID(`Blight`), characterclass.WizardClassID, 5},
	{SpellID(`Break Enchantment`), characterclass.WizardClassID, 5},
	{SpellID(`Cloudkill`), characterclass.WizardClassID, 5},
	{SpellID(`Cone of Cold`), characterclass.WizardClassID, 5},
	{SpellID(`Contact Other Plane`), characterclass.WizardClassID, 5},
	{SpellID(`Dismissal`), characterclass.WizardClassID, 5},
	{SpellID(`Dominate Person`), characterclass.WizardClassID, 5},
	{SpellID(`Dream`), characterclass.WizardClassID, 5},
	{SpellID(`Elemental Body II`), characterclass.WizardClassID, 5},
	{SpellID(`Fabricate`), characterclass.WizardClassID, 5},
	{SpellID(`False Vision`), characterclass.WizardClassID, 5},
	{SpellID(`Feeblemind`), characterclass.WizardClassID, 5},
	{SpellID(`Hold Monster`), characterclass.WizardClassID, 5},
	{SpellID(`Interposing Hand`), characterclass.WizardClassID, 5},
	{SpellID(`Mage's Faithful Hound`), characterclass.WizardClassID, 5},
	{SpellID(`Mage's Private Sanctum`), characterclass.WizardClassID, 5},
	{SpellID(`Magic Jar`), characterclass.WizardClassID, 5},
	{SpellID(`Major Creation`), characterclass.WizardClassID, 5},
	{SpellID(`Mind Fog`), characterclass.WizardClassID, 5},
	{SpellID(`Mirage Arcana`), characterclass.WizardClassID, 5},
	{SpellID(`Nightmare`), characterclass.WizardClassID, 5},
	{SpellID(`Overland Flight`), characterclass.WizardClassID, 5},
	{SpellID(`Passwall`), characterclass.WizardClassID, 5},
	{SpellID(`Permanency`), characterclass.WizardClassID, 5},
	{SpellID(`Persistent Image`), characterclass.WizardClassID, 5},
	{SpellID(`Planar Binding, Lesser`), characterclass.WizardClassID, 5},
	{SpellID(`Plant Shape I`), characterclass.WizardClassID, 5},
	{SpellID(`Polymorph`), characterclass.WizardClassID, 5},
	{SpellID(`Prying Eyes`), characterclass.WizardClassID, 5},
	{SpellID(`Secret Chest`), characterclass.WizardClassID, 5},
	{SpellID(`Seeming`), characterclass.WizardClassID, 5},
	{SpellID(`Sending`), characterclass.WizardClassID, 5},
	{SpellID(`Shadow Evocation`), characterclass.WizardClassID, 5},
	{SpellID(`Summon Monster 5`), characterclass.WizardClassID, 5},
	{SpellID(`Symbol of Pain`), characterclass.WizardClassID, 5},
	{SpellID(`Symbol of Sleep`), characterclass.WizardClassID, 5},
	{SpellID(`Telekinesis`), characterclass.WizardClassID, 5},
	{SpellID(`Telepathic Bond`), characterclass.WizardClassID, 5},
	{SpellID(`Teleport`), characterclass.WizardClassID, 5},
	{SpellID(`Transmute Mud to Rock`), characterclass.WizardClassID, 5},
	{SpellID(`Transmute Rock to Mud`), characterclass.WizardClassID, 5},
	{SpellID(`Wall of Force`), characterclass.WizardClassID, 5},
	{SpellID(`Wall of Stone`), characterclass.WizardClassID, 5},
	{SpellID(`Waves of Fatigue`), characterclass.WizardClassID, 5},
	{SpellID(`Acid Fog`), characterclass.WizardClassID, 6},
	{SpellID(`Analyze Dweomer`), characterclass.WizardClassID, 6},
	{SpellID(`Antimagic Field`), characterclass.WizardClassID, 6},
	{SpellID(`Bear's Endurance, Mass`), characterclass.WizardClassID, 6},
	{SpellID(`Beast Shape IV`), characterclass.WizardClassID, 6},
	{SpellID(`Bull's Strength, Mass`), characterclass.WizardClassID, 6},
	{SpellID(`Cat's Grace, Mass`), characterclass.WizardClassID, 6},
	{SpellID(`Chain Lightning`), characterclass.WizardClassID, 6},
	{SpellID(`Circle of Death`), characterclass.WizardClassID, 6},
	{SpellID(`Contingency`), characterclass.WizardClassID, 6},
	{SpellID(`Control Water`), characterclass.WizardClassID, 6},
	{SpellID(`Create Undead`), characterclass.WizardClassID, 6},
	{SpellID(`Disintegrate`), characterclass.WizardClassID, 6},
	{SpellID(`Dispel Magic, Greater`), characterclass.WizardClassID, 6},
	{SpellID(`Eagle's Splendor, Mass`), characterclass.WizardClassID, 6},
	{SpellID(`Elemental Body III`), characterclass.WizardClassID, 6},
	{SpellID(`Eyebite`), characterclass.WizardClassID, 6},
	{SpellID(`Flesh to Stone`), characterclass.WizardClassID, 6},
	{SpellID(`Forceful Hand`), characterclass.WizardClassID, 6},
	{SpellID(`Form of the Dragon I`), characterclass.WizardClassID, 6},
	{SpellID(`Fox's Cunning, Mass`), characterclass.WizardClassID, 6},
	{SpellID(`Freezing Sphere`), characterclass.WizardClassID, 6},
	{SpellID(`Geas/Quest`), characterclass.WizardClassID, 6},
	{SpellID(`Globe of Invulnerability`), characterclass.WizardClassID, 6},
	{SpellID(`Guards and Wards`), characterclass.WizardClassID, 6},
	{SpellID(`Heroism, Greater`), characterclass.WizardClassID, 6},
	{SpellID(`Legend Lore`), characterclass.WizardClassID, 6},
	{SpellID(`Mage's Lucubration`), characterclass.WizardClassID, 6},
	{SpellID(`Mislead`), characterclass.WizardClassID, 6},
	{SpellID(`Move Earth`), characterclass.WizardClassID, 6},
	{SpellID(`Owl's Wisdom, Mass`), characterclass.WizardClassID, 6},
	{SpellID(`Permanent Image`), characterclass.WizardClassID, 6},
	{SpellID(`Planar Binding`), characterclass.WizardClassID, 6},
	{SpellID(`Plant Shape II`), characterclass.WizardClassID, 6},
	{SpellID(`Programmed Image`), characterclass.WizardClassID, 6},
	{SpellID(`Repulsion`), characterclass.WizardClassID, 6},
	{SpellID(`Shadow Walk`), characterclass.WizardClassID, 6},
	{SpellID(`Stone to Flesh`), characterclass.WizardClassID, 6},
	{SpellID(`Suggestion, Mass`), characterclass.WizardClassID, 6},
	{SpellID(`Summon Monster 6`), characterclass.WizardClassID, 6},
	{SpellID(`Symbol of Fear`), characterclass.WizardClassID, 6},
	{SpellID(`Symbol of Persuasion`), characterclass.WizardClassID, 6},
	{SpellID(`Transformation`), characterclass.WizardClassID, 6},
	{SpellID(`True Seeing`), characterclass.WizardClassID, 6},
	{SpellID(`Undeath to Death`), characterclass.WizardClassID, 6},
	{SpellID(`Veil`), characterclass.WizardClassID, 6},
	{SpellID(`Wall of Iron`), characterclass.WizardClassID, 6},
	{SpellID(`Arcane Sight, Greater`), characterclass.WizardClassID, 7},
	{SpellID(`Banishment`), characterclass.WizardClassID, 7},
	{SpellID(`Control Undead`), characterclass.WizardClassID, 7},
	{SpellID(`Control Weather`), characterclass.WizardClassID, 7},
	{SpellID(`Delayed Blast Fireball`), characterclass.WizardClassID, 7},
	{SpellID(`Elemental Body IV`), characterclass.WizardClassID, 7},
	{SpellID(`Ethereal Jaunt`), characterclass.WizardClassID, 7},
	{SpellID(`Finger of Death`), characterclass.WizardClassID, 7},
	{SpellID(`Forcecage`), characterclass.WizardClassID, 7},
	{SpellID(`Form of the Dragon II`), characterclass.WizardClassID, 7},
	{SpellID(`Giant Form I`), characterclass.WizardClassID, 7},
	{SpellID(`Grasping Hand`), characterclass.WizardClassID, 7},
	{SpellID(`Hold Person, Mass`), characterclass.WizardClassID, 7},
	{SpellID(`Insanity`), characterclass.WizardClassID, 7},
	{SpellID(`Instant Summons`), characterclass.WizardClassID, 7},
	{SpellID(`Invisibility, Mass`), characterclass.WizardClassID, 7},
	{SpellID(`Limited Wish`), characterclass.WizardClassID, 7},
	{SpellID(`Mage's Magnificent Mansion`), characterclass.WizardClassID, 7},
	{SpellID(`Mage's Sword`), characterclass.WizardClassID, 7},
	{SpellID(`Phase Door`), characterclass.WizardClassID, 7},
	{SpellID(`Plane Shift`), characterclass.WizardClassID, 7},
	{SpellID(`Plant Shape III`), characterclass.WizardClassID, 7},
	{SpellID(`Polymorph, Greater`), characterclass.WizardClassID, 7},
	{SpellID(`Power Word Blind`), characterclass.WizardClassID, 7},
	{SpellID(`Prismatic Spray`), characterclass.WizardClassID, 7},
	{SpellID(`Project Image`), characterclass.WizardClassID, 7},
	{SpellID(`Reverse Gravity`), characterclass.WizardClassID, 7},
	{SpellID(`Scrying, Greater`), characterclass.WizardClassID, 7},
	{SpellID(`Sequester`), characterclass.WizardClassID, 7},
	{SpellID(`Shadow Conjuration, Greater`), characterclass.WizardClassID, 7},
	{SpellID(`Simulacrum`), characterclass.WizardClassID, 7},
	{SpellID(`Spell Turning`), characterclass.WizardClassID, 7},
	{SpellID(`Statue`), characterclass.WizardClassID, 7},
	{SpellID(`Summon Monster 7`), characterclass.WizardClassID, 7},
	{SpellID(`Symbol of Stunning`), characterclass.WizardClassID, 7},
	{SpellID(`Symbol of Weakness`), characterclass.WizardClassID, 7},
	{SpellID(`Teleport Object`), characterclass.WizardClassID, 7},
	{SpellID(`Teleport, Greater`), characterclass.WizardClassID, 7},
	{SpellID(`Vision`), characterclass.WizardClassID, 7},
	{SpellID(`Waves of Exhaustion`), characterclass.WizardClassID, 7},
	{SpellID(`Antipathy`), characterclass.WizardClassID, 8},
	{SpellID(`Binding`), characterclass.WizardClassID, 8},
	{SpellID(`Charm Monster, Mass`), characterclass.WizardClassID, 8},
	{SpellID(`Clenched Fist`), characterclass.WizardClassID, 8},
	{SpellID(`Clone`), characterclass.WizardClassID, 8},
	{SpellID(`Create Greater Undead`), characterclass.WizardClassID, 8},
	{SpellID(`Demand`), characterclass.WizardClassID, 8},
	{SpellID(`Dimensional Lock`), characterclass.WizardClassID, 8},
	{SpellID(`Discern Location`), characterclass.WizardClassID, 8},
	{SpellID(`Form of the Dragon III`), characterclass.WizardClassID, 8},
	{SpellID(`Giant Form II`), characterclass.WizardClassID, 8},
	{SpellID(`Horrid Wilting`), characterclass.WizardClassID, 8},
	{SpellID(`Incendiary Cloud`), characterclass.WizardClassID, 8},
	{SpellID(`Iron Body`), characterclass.WizardClassID, 8},
	{SpellID(`Irresistible Dance`), characterclass.WizardClassID, 8},
	{SpellID(`Maze`), characterclass.WizardClassID, 8},
	{SpellID(`Mind Blank`), characterclass.WizardClassID, 8},
	{SpellID(`Moment of Prescience`), characterclass.WizardClassID, 8},
	{SpellID(`Planar Binding, Greater`), characterclass.WizardClassID, 8},
	{SpellID(`Polar Ray`), characterclass.WizardClassID, 8},
	{SpellID(`Polymorph Any Object`), characterclass.WizardClassID, 8},
	{SpellID(`Power Word Stun`), characterclass.WizardClassID, 8},
	{SpellID(`Prismatic Wall`), characterclass.WizardClassID, 8},
	{SpellID(`Protection from Spells`), characterclass.WizardClassID, 8},
	{SpellID(`Prying Eyes, Greater`), characterclass.WizardClassID, 8},
	{SpellID(`Scintillating Pattern`), characterclass.WizardClassID, 8},
	{SpellID(`Screen`), characterclass.WizardClassID, 8},
	{SpellID(`Shadow Evocation, Greater`), characterclass.WizardClassID, 8},
	{SpellID(`Shout, Greater`), characterclass.WizardClassID, 8},
	{SpellID(`Summon Monster 8`), characterclass.WizardClassID, 8},
	{SpellID(`Sunburst`), characterclass.WizardClassID, 8},
	{SpellID(`Symbol of Death`), characterclass.WizardClassID, 8},
	{SpellID(`Symbol of Insanity`), characterclass.WizardClassID, 8},
	{SpellID(`Sympathy`), characterclass.WizardClassID, 8},
	{SpellID(`Telekinetic Sphere`), characterclass.WizardClassID, 8},
	{SpellID(`Temporal Stasis`), characterclass.WizardClassID, 8},
	{SpellID(`Trap the Soul`), characterclass.WizardClassID, 8},
	{SpellID(`Astral Projection`), characterclass.WizardClassID, 9},
	{SpellID(`Crushing Hand`), characterclass.WizardClassID, 9},
	{SpellID(`Dominate Monster`), characterclass.WizardClassID, 9},
	{SpellID(`Energy Drain`), characterclass.WizardClassID, 9},
	{SpellID(`Etherealness`), characterclass.WizardClassID, 9},
	{SpellID(`Foresight`), characterclass.WizardClassID, 9},
	{SpellID(`Freedom`), characterclass.WizardClassID, 9},
	{SpellID(`Gate`), characterclass.WizardClassID, 9},
	{SpellID(`Hold Monster, Mass`), characterclass.WizardClassID, 9},
	{SpellID(`Imprisonment`), characterclass.WizardClassID, 9},
	{SpellID(`Mage's Disjunction`), characterclass.WizardClassID, 9},
	{SpellID(`Meteor Swarm`), characterclass.WizardClassID, 9},
	{SpellID(`Power Word Kill`), characterclass.WizardClassID, 9},
	{SpellID(`Prismatic Sphere`), characterclass.WizardClassID, 9},
	{SpellID(`Refuge`), characterclass.WizardClassID, 9},
	{SpellID(`Shades`), characterclass.WizardClassID, 9},
	{SpellID(`Shapechange`), characterclass.WizardClassID, 9},
	{SpellID(`Soul Bind`), characterclass.WizardClassID, 9},
	{SpellID(`Summon Monster 9`), characterclass.WizardClassID, 9},
	{SpellID(`Teleportation Circle`), characterclass.WizardClassID, 9},
	{SpellID(`Time Stop`), characterclass.WizardClassID, 9},
	{SpellID(`Wail of the Banshee`), characterclass.WizardClassID, 9},
	{SpellID(`Weird`), characterclass.WizardClassID, 9},
	{SpellID(`Wish`), characterclass.WizardClassID, 9},
}

func mustBuildCoreSpellListEntries(seeds []spellListEntrySeed) []SpellListEntry {
	entries := make([]SpellListEntry, 0, len(seeds))
	seen := make(map[spellListEntryKey]struct{}, len(seeds))

	for _, seed := range seeds {
		entry, ok := NewSpellListEntry(seed.spellID, seed.classID, seed.spellLevel)
		if !ok {
			panic("invalid core spell list entry seed")
		}

		key := spellListEntryKey{
			spellID:    entry.GetSpellID(),
			classID:    entry.GetClassID(),
			spellLevel: entry.GetSpellLevel(),
		}
		if _, ok := seen[key]; ok {
			panic("duplicate core spell list entry seed")
		}

		seen[key] = struct{}{}
		entries = append(entries, entry)
	}

	return entries
}

type spellListEntryKey struct {
	spellID    SpellID
	classID    characterclass.ClassID
	spellLevel int
}
